### ISSUE TITLE
Thermistor tables are not correct for AiO boards under 20 degres and give defect temp error

### ISSUE THREAD

**Issue by luc-github** [luc-github/Repetier-Firmware-0.92#11]
Thermistor tables are not correct for AiO boards under 20 degres and give defect temp error

**Comment by luc-github** [comment]
New table for bedGen 0 & Gen 1 is implemented https://github.com/luc-github/Repetier-Firmware-0.92/commit/07715315abae88aafbd8b7832cd80ca7131ea280

New table for Extruder Gen 0 is also implemented 
No new table for Extruder Gen 1

Check https://github.com/luc-github/Repetier-Firmware-0.92/blob/master/bed-extruder-tables.xlsx

**Comment by garry572** [comment]
Hi Luc I also generated tables for extruder and bed for my 1.0 I did notice one small issue with my 1.0  bed.. I have access to a multichannel temperature probe, so I attached 3 sensors on the table to measure the temperature.  Depending on the temperature , there is up to a 7C difference in temperatures over the table during heating, after the temperature is stabilized over 5 mins these equalized out to withing 0.8C

**Comment by luc-github** [comment]
Hi Garry, to update bed table, I relied on David work, check here https://github.com/luc-github/Repetier-Firmware/issues/83
He did a lot of measurement minimizing the environment effect, including stabilization time like you mention.
