### ISSUE TITLE
Change Thermistor

### ISSUE THREAD

**Issue by gamecompiler** [luc-github/Repetier-Firmware-0.92#122]
Hi, id installed a e3Dv6 in my printer with bowden successfully.
(Id got everything working, steps per mm e.t.c, but not the thermistor)
But, i need to change the Thermistor type, normally id would have to change this settings:

EXT1_TEMPSENSOR_TYPE = 8 // 8 is ATC Semitec 104GT-2

But nothing changes.... In a room with 21 degress it shows that i have 85 degress inside.
Is EXT1_TEMPSENSOR_TYPE defined elsewhere ? Id searched for it, but i did not find sth.

(Id also tryed to define other thermistors in firmware , if sth may change, no effect...)

Thanks in advance

**Comment by luc-github** [comment]
it is in the FAQ : https://github.com/luc-github/Repetier-Firmware-0.92/issues/104

**Comment by gamecompiler** [comment]
Ok thank you very much.
I will build a heating tool for the extruder to get the data.

I will upload my table when im done in the FAQ issue.
