### ISSUE TITLE
Forgive me for a stupid question,  But... 

### ISSUE THREAD

**Issue by firedrake150** [luc-github/Repetier-Firmware-0.92#129]
What flashing settings and EEPROM junction should I short for a DaVinci 2.0 Duo (NOT 2.0A.) Dual PLA capable extruders,  Dual fans.   there are 2, maybe 3 silkscreened pin groups that look like they could be the ones to short.  Please assist,  And is there anything else I should watch out for for this reflash?

**Comment by luc-github** [comment]
Duo 2.0 jumper is JP1 - Pins may not bepopulated but jump the contact points is working
Check readme for complete process and/or have a look to youtube video mentioned in readme

**Comment by firedrake150** [comment]
Alright.   Thanks.   ^^  I'll look into it next time I have the chance.
