### ISSUE TITLE
Printer is not recognised in Windows after install of 0.92 on Davinci 1.0

### ISSUE THREAD

**Issue by blackmambazaa** [luc-github/Repetier-Firmware-0.92#13]
Issue:

- I have uploaded 0.92 on to my Davinci 1.0 and the printer isn't recognised in Windows anymore.
- Before the upload, the device showed up as a Bossa... but now it just says Unknown Device.
- I also verified that the firmware has successfully installed on the printer by cycling through the menus on the printer itself.

Steps taken to try to resolve the communication issue:

- I had installed the Sam-ba and Due drivers but none seem to resolve the "Unknown Device" issue.

Any ideas?

**Comment by luc-github** [comment]
Normally it is Arduino Due - drivers is in Arduino IDE 
what version of IDE did you used to compile and flash ?

**Comment by drbogger** [comment]
Yup, that happens if you don't use the variant.cpp file that's included.

**Comment by blackmambazaa** [comment]
I had used IDE version 1.5.8 and the drivers within that. 
I also used the variant.cpp included in the firmware package.

I guess it won't hurt to try the install again hey. I will post back my findings.

**Comment by drbogger** [comment]
I had issues getting the variants.cpp to work with the arduino install package.. try using the .zip version, and see if it works that way.

**Comment by luc-github** [comment]
looking at https://github.com/luc-github/Repetier-Firmware-0.92/issues/14
I thinks something is wrong in installation, check if variant.cpp is same as fw one to be sure copy is well done

**Comment by blackmambazaa** [comment]
Can you please post your variants.cpp file here. I want to compare it to mine.

**Comment by luc-github** [comment]
my variants.cpp is the same as FW
https://github.com/luc-github/Repetier-Firmware-0.92/blob/master/src/ArduinoDUE/AdditionalArduinoFiles/1.5.8/hardware/arduino/sam/variants/arduino_due_x/variant.cpp

**Comment by blackmambazaa** [comment]
Scratch that. I re-flashed and uploaded 0.92 to the printer. All is well. The Due drivers are recognised now and I am able to communicate with the printer.

Thanks for the help.

**Comment by trix8687** [comment]
i am having this problem. i have reflashed 3 times now

**Comment by luc-github** [comment]
OS ? did you copy variant.cpp / usbcore.cpp ? arduino ide version ? how do you got 0.92 : git-hub or Zip ?

**Comment by trix8687** [comment]
Window 7 64, yes i copied both. arduino ide 1.5.8, zip, not 100% sure it is the da vinci 1.0 came with version 1.0.1

**Comment by luc-github** [comment]
you have micro SD or normal SD Card reader ?

**Comment by trix8687** [comment]
micro

**Comment by luc-github** [comment]
so it is 1.0A

**Comment by trix8687** [comment]
i assumed as much. i did make that change in configuration.h

**Comment by luc-github** [comment]
check you copied properly the variant.cpp in C:\Program Files (x86)\Arduino\hardware\arduino\sam\variants\arduino_due_x

download zip again - it may be corrupted

**Comment by trix8687** [comment]
just to confirm, i am copying varriant from the zip file to Arduino\hardware\arduino\sam\variants\arduino_due_x,
yes?

**Comment by luc-github** [comment]
yes in zip there is one for 1.5.8 and one for 1.6.0 copy the one for 1.5.8 to C:\Program Files (x86)\Arduino\hardware\arduino\sam\variants\arduino_due_x

**Comment by trix8687** [comment]
still no dice. windows recognizes it as USB composite device and cannot install drivers

**Comment by trix8687** [comment]
My arduino directory is D:\Program Files (x86)\Arduino. That shouldnt be an issue, should it?

**Comment by luc-github** [comment]
no as I wrote earlier :  C:\Program Files (x86)\Arduino\hardware\arduino\sam\variants\arduino_due_x

I have win7 64bits also

reinstall arduino 1.5.8 then copy again the varian.cpp / usbcore.cpp as they are erased when reinstalling

there is no reason the arduino drivers is not installed especially if Arduino IDE see the correct port COM

**Comment by trix8687** [comment]
still nothing

**Comment by trix8687** [comment]
this is crazy. it recognizes it before i flash it, but after, the firmware is working on the printer, but windows wont connect.

**Comment by luc-github** [comment]
ho wait - fw is ok on printer - no black bar ?

**Comment by trix8687** [comment]
no, temps showing , printer is ready.... all the menus are correct

**Comment by luc-github** [comment]
ok this is different then
it is windows mess - not FW
the drivers are in C:\Program Files (x86)\Arduino\drivers
select the unknow drivers by these ones

**Comment by trix8687** [comment]
i dont see the drivers

**Comment by luc-github** [comment]
you do not have 
C:\Program Files (x86)\Arduino\drivers\arduino.inf

**Comment by trix8687** [comment]
i have that, what do i need to do with it?

**Comment by luc-github** [comment]
use it to update the unknown or wrong selected drivers
what your device manager says ?

**Comment by trix8687** [comment]
ok, i think i got it, sorry im no good with drivers. i'll let you know how that goes

**Comment by trix8687** [comment]
"the best driver for your device is already installed"
 "USB Composite Device"

**Comment by trix8687** [comment]
still not working

**Comment by luc-github** [comment]
update it manually by selecting "browse my computer for drivers software" then select the C:\Program Files (x86)\Arduino\drivers

**Comment by trix8687** [comment]
i did. thats when it says "the best driver for your device is already installed"
"USB Composite Device"

**Comment by luc-github** [comment]
is this COM disapear when you unplug the printer ?

**Comment by trix8687** [comment]
the COM disappears when i flash the firmware

**Comment by luc-github** [comment]
is this COM disapear when you unplug the printer ?

**Comment by luc-github** [comment]
when you plug printer a device appear in device manager
when you unplug printer a device disappear in device manager

**Comment by trix8687** [comment]
the "USB Composite device" disappears when i unplug it, yes

**Comment by luc-github** [comment]
OK then try to uninstall it - then unplug and replug the printer
when the printer will be detected It may ask for drivers so you can select the arduino one

**Comment by trix8687** [comment]
ok, it appears to may have been a problem with that usb port, i swapped it with one my regular printer was plugged in and it is showing up as arduino Due (COM4)

**Comment by luc-github** [comment]
I read somewhere using USB 3.0 port is not worling well but no issue with 2.0

**Comment by luc-github** [comment]
at least you can use any host now printer port is working - should be ok

**Comment by trix8687** [comment]
thanks for all the help anyway

**Comment by garry572** [comment]
yes i had trouble with a usb3 port, but work fine on usb2

**Comment by luc-github** [comment]
Thanks Garry I forgotten where I read that - was from you ^_^

**Comment by Weisbrot237** [comment]
I Got the same Problem. but i dont even have USB 3.0 on my pc. only USB 2.0
i tried every usb port i have. on 2 it shows "unknown device" and on the rest it shows "USB Composite Device"
someone got a idea?

**Comment by alexkaps** [comment]
Same for me, but with an accidental board short circuit. Now black lines in lcd , nothing in Ports and this in device manager "Windows has stopped this device because it has reported problems. (Code 43)".  Is there any doctor or there is no hope?

**Comment by luc-github** [comment]
@alexkaps  Please have a look at http://voltivo.com/forum/davinci-peersupport/734-1-0a-no-power-to-extruder-heater-fix and other related threads

**Comment by alexkaps** [comment]
thank you luc, just before the darkness i had the same extruder decoupled message. and while trying to locate the R271 fuse\resistor i had the "board jump". I 'm not 100% sure of jumping the pins because i was not looking, but everything lost.

**Comment by luc-github** [comment]
NP let me know if you still have decoupled issue after the fix

**Comment by luc-github** [comment]
Ho just to confirm did you jump JP1 or JP37 according your printer type ? - you may just need a reset / reflash

**Comment by alexkaps** [comment]
Yes i jumped J37 and i have to reflash if everything goes well. I just bridge/solder the R271 and add a new fuse at the extruder's cable, right?  Could this fuse be a 5A car fuse?
lol it's the only one i got right now.

**Comment by alexkaps** [comment]
I did the above and now have continuity between my 12V supply and the left white cable below R271. 
I still get the usb device not recognized error and nothing on ports.  Should the left white cable have continuity with the ground pin? Because it hasn't if it matters.

**Comment by luc-github** [comment]
I am not an expert for board fix, sorry - you may post your issue on soliforum and voltivo forum, there are a lot of expert of Davinci Electronic there -  they will confirm the next steps better than me

**Comment by alexkaps** [comment]
I ve already post it but you are the only one answered so far. :)  I was considering  changing my board to ramps 1.4 but information i ve found is still elusive to me, so doing more research. If i fix my problem i ll post it here just in case someone have the same problem. Keep up the good work! Thank you.

**Comment by luc-github** [comment]
several people change to mega/ramps but you also need to change endstop and screen/keypad in this case

**Comment by luc-github** [comment]
FYI - If you are in US and it is MCU issue - this can be fixed also - some guys proposed to do it

**Comment by alexkaps** [comment]
Yes, but changing to ramps is my only hope so far. I think you are referring to Keith from Voltivo, but unfortunately for my printer i'm in Greece.

**Comment by luc-github** [comment]
the best for HW is here http://voltivo.com/forum/davinci-hwmods/509-my-arduino-ramps-install?start=20#4558
But depending of your ramps knowledge is may not be enough

**Comment by alexkaps** [comment]
Thanks!

**Comment by alexkaps** [comment]
I 've found a ramps 1.4 + lcd + controller/ mega arduino 2560 / thermistor 100K and i ll change the board the day after tomorrow. I ll try to document the process in simple steps if possible.  One question though, What will this version of repetier need to work with ramps setup? I'm referring to FAQ#110: "the AVR part (Mega/Ramps) is not done but could be done with few changes to keep UI and DaVinci features"

**Comment by luc-github** [comment]
You also need to change the endstop - Davinci ones won't work as all electronic is on board not on endstop

about AVR version yes can be done, it is actually a code cleanup as 90% is common betweeb due and avr, and several feature like EEPROM on SDCard is not necessary on ramps - it is in my TODO list but not top priority, I have more urgent topics to be done first unfortunatly

**Comment by alexkaps** [comment]
yes, everything i needed will cost about 120euros (ramps,mega,lcd,endstops,drivers,thermistor,resistor for led, cables + extra sd ramps and a 0.25 nozzle )

No worries about the avr, your contribution is great both here and in forums :) Looking forward for a complete integration of rep though, when you find the time.  

What should i do with the stock motherboard? 
It's a probably fried 1.0A (J37) with soldered R271.

**Comment by luc-github** [comment]
well you may want to bring to local electronic shop and ask them for repair, in worst case need to change MCU - they can do it

**Comment by trix8687** [comment]
Next person that responds to these emails, please remove me from the list
of emails.

**Comment by luc-github** [comment]
sorry no list - it is because you are in thread  - you may unwatch repository to unsuscribe update

**Comment by GoingOffRoading** [comment]
Can you keep me on this list ; )  This firmware is amazing and the community is truly grateful for the work you've put in and continue to deliver.  Thank you!

**Comment by luc-github** [comment]
Thanks but notification is managed by each user :
![image](https://cloud.githubusercontent.com/assets/8822552/12314784/d1d4d4fc-baae-11e5-9efb-02c3e631790a.png)
