### ISSUE TITLE
No support for M17/M18 Gcodes

### ISSUE THREAD

**Issue by henry-id** [luc-github/Repetier-Firmware-0.92#133]
Pretty common command, and quite useful.

There's already a menu option to do it, so I really can't figure out why it can't support these Gcodes.

I'm currently looking into enabling it for myself, but this coding is a level above me right now.

**Comment by luc-github** [comment]
what do these commands ?
they are not in repetier FW
https://github.com/repetier/Repetier-Firmware/blob/work092/src/ArduinoDUE/Repetier/Repetier.ino

**Comment by luc-github** [comment]
Are the reprap command for enable / disable motor  ? repetier is M84

**Comment by luc-github** [comment]
Any update or  can I close issue ?

**Comment by clowrey** [comment]
I would appreciate M18 support too as Simplify3D uses this command for its "disable motors" button in machine control panel, which does nothing on repetier. But manual M84 does work, so maybe the M84 command could also be used for M18?

**Comment by luc-github** [comment]
no need it is,  just wrong default setting in S3D which can be modified
![image](https://cloud.githubusercontent.com/assets/8822552/25694430/ecd4aaee-30ae-11e7-95bb-3a223b6d21e6.png)

**Comment by clowrey** [comment]
Ahh I see, thanks for the hint on that. Is there any easy way to replace the M17 "enable motor" command with an equivalent in Repetier?

**Comment by luc-github** [comment]
https://github.com/luc-github/Repetier-Firmware-0.92/issues/105
repetier automaticaly enable motors when used so there is no enable motor command

**Comment by clowrey** [comment]
I see.. might be nice to have enable if you just want them to hold position without moving. But I understand it is not 100% necessary

**Comment by luc-github** [comment]
in that case you just send command to move of 0 position it should do the trick

**Comment by clowrey** [comment]
If anyone has edit privileges on this page http://reprap.org/wiki/G-code the section on M18 for Repetier could be updated to say "use M84" like Marlin has, instead of "No" like currently.
