### ISSUE TITLE
2 inches Stonewalled / Unusable space

### ISSUE THREAD

**Issue by firedrake150** [luc-github/Repetier-Firmware-0.92#136]
So,  I've been having a lot of trouble after getting the firmware successfully flashed on my 2.0 duo.   

So initially I was having trouble getting it to a moving the y axis and then getting a tunnel y axis shifting and I tried reducing acceleration and reducing and tightening some other parts too no success so then I swap around the motor driver boards being careful of their orientation so as not to fry anything and I got the printer to us stop with the taxes shifting again but I had to recalibrate some things and retouch some things because it was using you know in proper settings for the motors so after that I ended up using both Kira and slicer within repeti or host trying to get it to successfully print and I had a feeling that was somewhat successful a few of them that had some failures pieces and some turtles made print and then I just had you know film and jamming. The jamming occurs in both extruders and what I call stonewalling or the printer not going beyond the first two inches of the y axis of the print bed is occurring and I'm not sure exactly what to do to fix that but it will not go past a certain line that is 2 inches in from the outside edge of the y axis of the bed so at the very front of the printer I could set an object that's an inch you know I'm not on that bed and have nope no trouble with it getting in the way or anything because it will not print there and I've actually had prints that slice fine and cure a slice fine and slicer and they failed to print properly because they're smashing against that line and I'm not sure what setting I have that might not be correct. Both extruders are jamming onPETG and PLA and ABS filaments.   I need some help if anyone is willing to provide it I am at a loss as to what I can try and what I can correct any any assistance would be a greatly appreciated.

**Comment by luc-github** [comment]
Well looks like you have issue with yours slicers settings - if you have duo 2.0 (Normal SDCard) or not 2.0A(micro SDCard) I can confirm you, FW is fine and defaults settings are fine, do not change them- just second extruder calibration is necessary to fine tune position but this is not your issue currently.
Also I guess this happen with stock extruder and stock thermistor.

I would suggest to post your slicers settings to voltivo forum (http://voltivo.com/index) or soliforum (.soliforum.com/forum/21/xyz-printing-davinci/) there are users who use same slicers as you 

I do not use kira / repetier host (Slic3r/cura) slicers so I won't be able to help, and this issue tracker is more for FW issues - so you won't get lot of help I am afraid

I only can say - check your bed level, your temperature extrusion in slicer and bed size in slicer.
