### ISSUE TITLE
Davinci 1.0 periodically restarts after installation of 0.92

### ISSUE THREAD

**Issue by blackmambazaa** [luc-github/Repetier-Firmware-0.92#14]
After flashing the EEPROM and uploading 0.92 onto my Davinci 1.0, I am able to see that the firmware has successfully installed on the printer, but the issue that I am experiencing is that the printer restarts every 25 seconds.

So whether the printer is idling or whether I am in a menu, it still restarts.

I have one of the newer boards that had 1.1j as the default firmware on it.

Any ideas?

**Comment by luc-github** [comment]
This is the watchdog - looks you have watchdof enabled but somehow it is not reset

**Comment by blackmambazaa** [comment]
Is the watchdog like a "Stay awake" type of feature?

**Comment by luc-github** [comment]
I suggest to first disable watchdog, it is in variant.cpp, to see what is wrong

**Comment by luc-github** [comment]
watchdog is a checker printer is not in dead loop by regular ping - if no ping is done within 15 s it reset printer

**Comment by blackmambazaa** [comment]
Okay, good news is that I flash the EEPROM and uploaded 0.92 again. It no longer restarts due to the watchdog.

Turns out that I had uploaded "repetier-firmware-davinci" instead of 0.92-master. Apologies. 

Thanks for the help.

**Comment by luc-github** [comment]
ho you used the 0.91 - so yes make sense for the issue

**Comment by blackmambazaa** [comment]
Yip I had 0.91 in the same parent folder as 0.92. Recipe for disaster

**Comment by luc-github** [comment]
Well issue is solved - this is the key point - enjoy
