### ISSUE TITLE
EEPROM option not available!?

### ISSUE THREAD

**Issue by Hecot** [luc-github/Repetier-Firmware-0.92#146]
I posted this question also to the repetier forum, but didn't get any response so far. I know that this is a bit off-topic here, but I hope someone will answer this question:

I'm running Repetier host V1.6.1 on two computers - one desktop, one laptop - both Win7-pro 64-bit. With both computers I can send commands to the printer (DaVinci 1.0A with 0.92 firmware) - all work well with one exception: On the deskop computer I can access the EEPROM of the printer, but on the laptop this option is not available (it's just light gray and could not be selected)!?

The only difference I can see is that the laptop got the Arduino software for flashing the firmware on it, on the desktop there is only the Repetier host software installed. Could this be the reason that the Arduino software or driver settings will cause not allowing to access the EEPROM? Or is there a special option for accessing the EEPROM.

If this would be the case, what would be the countermeasure so I have access to the EEPROM also with my laptop?

Thanks and sorry for bothering you with this off-topic question!

**Comment by luc-github** [comment]
No - I guess it is more a setting in repetier host
does M205 works on both ?

**Comment by Hecot** [comment]
Dear Luc,

M205 is working and I can send commands to the printer ... but still can't access the EEPROM from Repetier host ... the option stays gray!

![host](https://cloud.githubusercontent.com/assets/11699283/13885587/7ee5412a-ed33-11e5-8d53-453932eb3643.png)

**Comment by luc-github** [comment]
looks like repetier host is waiting for something enable it
I never got issue - did you try to disconnect and connect to see what display in serial log ?

**Comment by Hecot** [comment]
Here is the display of the log from disconnecting and connecting again!

![host2](https://cloud.githubusercontent.com/assets/11699283/13886477/5427b338-ed37-11e5-8cb7-5a495baca904.png)

**Comment by luc-github** [comment]
check your communication settings / or try another usb port, you may need to decrease the baud rate, seems you got "ile" istead of "file" and "wai" instead of "wait", so it is obvious you have communication issue

**Comment by Hecot** [comment]
Dear Luc,

I reduced the Baud rate to lowest value 9600 ... makes no difference - I tried a different cable and USB port, but still have this lost letters in the serial port console. Once out of a sudden the EEPROM option was available but when pressing the button it took 20 seconds to load the values ... some of them became red (never seen this before). When trying a second time it's back gray again ... 

Looks like there are serious communication problems ... but beside what I have tried I see no other help! Do you have any more idea how to solve this? Strange that on my Desktop it's working fine ... maybe there is a grounding issue?

**Comment by luc-github** [comment]
I think you USB has some noise - laptop USB are more sensitive because everything is smaller and close compare to Desktop and if EMI is not correct you may have noise on signal.

be sure printer and pc/host  use same speed (115200 is usually ok ) 

Some Idea : 
- check if you have some option in BIOS for USB you can play 
- Be sure you wifi / bluetooth are off and no ethernet cable around same for AC adaptor cable or even light cable, all these can bring noise

**Comment by luc-github** [comment]
If no more question - please close issue

**Comment by Hecot** [comment]
I tried all that come to my mind - switched off every power consuming devices like lightning, wifi etc. still have the same issue of unstable connection! Anyway - I'm closing this isssue as I think it will only regard my poor Macbook!
