### ISSUE TITLE
Cannot control the printer via Repetier on 0.92

### ISSUE THREAD

**Issue by blackmambazaa** [luc-github/Repetier-Firmware-0.92#16]
Hi,

I cannot  control the printer via Repetier-host, but I am able to do basic movements on the extruder using Pronterface.

In Repetier-host, I am able to configure everything and select the correct com port, but that's about it.

If I click on Manual Control and thereafter click on the connect button, the status changes from disconnected to idle and it says "8 commands waiting".

Any ideas what this could be related to?

**Comment by luc-github** [comment]
yes repetier host is not properly setup

check http://voltivo.com/forum/davinci-peersupport/501-da-vinci-setup-guide-from-installation-to-wireless-printing#3773
and http://voltivo.com/forum/davinci-firmware/148-your-configuration

**Comment by blackmambazaa** [comment]
Ah, I didn't save the settings to the EEPROM. I did that now within the settings menu on the printer.

Thanks for the tip.
