### ISSUE TITLE
New alpha version based on 0.92.10 Compatible with the Scanner?

### ISSUE THREAD

**Issue by Lehmii** [luc-github/Repetier-Firmware-0.92#171]
I read here that the repeating 0.92.10 Compatible with the Scanner from the AiO can now be used ...

New alpha version based on 0.92.10 is ready for test here

     Multilangue: globe_with_meridians:
     AiO support for scanner: camera: <------------
     Better auto leveling: tractor:

**Comment by luc-github** [comment]
Hardware is supported laser / led / turntable 
https://github.com/luc-github/Repetier-Firmware-0.92/tree/0.92.6-sync
AiO scanner support is present in FW but scanner software support is currently basic, horus is a good candidat, feel free to help

**Comment by Lehmii** [comment]
Can I take the scanner software of XYZ?

It surprises me only that Arduino is not supported?
[URL=http://www.directupload.net/file/d/4412/6upctc2f_png.htm][IMG]http://fs5.directupload.net/images/160710/temp/6upctc2f.png[/IMG][/URL]

**Comment by luc-github** [comment]
no - XYZ software is not supported - @zeus10 is working on Horus support (https://github.com/bqlabs/horus) which is the candidate currently

**Comment by luc-github** [comment]
what are these links ? - cannot see  
what means : 
>It surprises me only that Arduino is not supported?

**Comment by luc-github** [comment]
Ok saw the picture :
yes 4 for AiO (WITH NO SCANNER SUPPORT) because support is not 100% because no software so better to warn people who read the readme too fast

but what means :

>It surprises me only that Arduino is not supported?

**Comment by Lehmii** [comment]
Thanks for the info, I'm still waiting for the FW.

**Comment by luc-github** [comment]
ok so I close topic
