### ISSUE TITLE
Question: Reset necessary for updating firmware changes or upgrade?

### ISSUE THREAD

**Issue by opensourcefan** [luc-github/Repetier-Firmware-0.92#173]
Sorry, I feel this is too simple of a question but I can't find the answer on any installation page. 

Do I need to perform a reset via the jumpers to flash an update or can I simply flash over top of an already Repetier flashed Da Vinci? I want to make a quick configuration change (re-purpose fan).

**Comment by luc-github** [comment]
jumper is only to wipe xyz fw, after no need anymore.

**Comment by opensourcefan** [comment]
Thank you very much for the quick reply. Could that be added to the first line of the installation instructions maybe?

**Comment by opensourcefan** [comment]
I can submit it if you prefer.

**Comment by luc-github** [comment]
I just did on master - please confirm it is clear for you so i will apply on devt also

Thank you

**Comment by opensourcefan** [comment]
Yes, that is very clear, thank you.

**Comment by luc-github** [comment]
thank you for pointing this out ^_^

**Comment by opensourcefan** [comment]
Anytime, thank you for all your hard work.

**Comment by luc-github** [comment]
thank you - just do not forget to load fail safe or M502/M500 after update, as EEPROM content may change due to update

**Comment by opensourcefan** [comment]
Ah, yes, that can be easily forgotten. ;)

**Comment by luc-github** [comment]
I close issue if no more update
