### ISSUE TITLE
Flashed Da Vinci 1.1 plus - Help

### ISSUE THREAD

**Issue by polarnomad** [luc-github/Repetier-Firmware-0.92#177]
Hello i think i just bricked a 1.1 plus??? I flashed the chip to load the Repetier firmware and the firmware won't load, after reading more post found that the 1.1 plus is not compatible. Is there any thing i can do to load the Repelier firmware o recover the unit to the original firmware?

Any guidance would be most welcome.

Thanks in advance

**Comment by luc-github** [comment]
Yes 1.1 is not supported - https://github.com/luc-github/Repetier-Firmware-0.92/issues/106
I think the chip is same as 1.0 (SAM3X8E)  but I am not sure, as I never saw the board. also screen and wifi   are new feature that for sure are not implemented in current FW.

Also I am pretty  sure 1.1 plus is same as new generation1.0A/2.0A/AiO => no way to revert stock FW as it is encrypted

I suggest you to contact XYZ and say you let your computer printer "power on" all night and then there was a power cut during night and when you  saw your printer on morning it was like this

They will ask to send back the board or the full printer in worst case

This is the best advice I can give you sorry - next one is to be sure the device you flash is supported before you flash it - even ask questions - it will avoid you a lot of trouble - good luck
