### ISSUE TITLE
Extruder table is not correct for 19 degres for 1.0a

### ISSUE THREAD

**Issue by luc-github** [luc-github/Repetier-Firmware-0.92#18]
Extruder table is not correct for 19 degres for 1.0a it generate a sensor error

**Comment by luc-github** [comment]
I cannot test so need feedback for tweaking
I have modified the thermistor table of 1.0a in testing branch 
![image](https://cloud.githubusercontent.com/assets/8822552/5622322/b7dd44c4-957c-11e4-9e7a-5765db227794.png)

![image](https://cloud.githubusercontent.com/assets/8822552/5622309/71bc95f8-957c-11e4-8131-aecfd579d340.png)

**Comment by superdavex** [comment]
I am testing this now. My temps are staying above 0 before the patch so I'll have to wait to see if they come back down.

**Comment by luc-github** [comment]
the goal is to have bed temperature and extruder temperature identical or +/-1 degres at room temperature

**Comment by superdavex** [comment]
They actually are now showing the same value.    After the patch they are both 21c.  I'll keep a watch on them.

**Comment by luc-github** [comment]
Great - yes now need to check in early morning when temperature is cold and printer is cold also
wait for your feedback

**Comment by superdavex** [comment]
I can confirm now the patch corrects the temperature for values in the 16 to 19 range.  It is now within one degree of the bed temp.

**Comment by luc-github** [comment]
Ok great - l will implement it in master then

Thanks

**Comment by Doudou14** [comment]
Is the firmware running on 1.0A? (Except the temperature error)

**Comment by superdavex** [comment]
Yes, I am running on 1.0A.  The latest table update fixes the low temp error.

**Comment by luc-github** [comment]
blackmambazaa has also a 1.0a and run fw without issue

**Comment by luc-github** [comment]
fix implemented in master https://github.com/luc-github/Repetier-Firmware-0.92/commit/4cea0ea717c4fd1011e910314e674c43371a8c3e
