### ISSUE TITLE
Extruder hitting the glass

### ISSUE THREAD

**Issue by Legendaire** [luc-github/Repetier-Firmware-0.92#181]
I broke down and flashed my 1.0A to Rep .92.  After sweating if it would work everything went without a hitch until I tried to print.  Now my nozzle is scrapping across the glass.  The extruder motor is clicking until I move the build plate down.  At that time the extruder works fine.  Obviously the extruder nozzle is too close to the build plate.  How does one fix this?
I have tried RepHost 1.6.2 and Slic3r.  I'm pondering just buying Simplify3D to see if that fixes my issue.

**Comment by luc-github** [comment]
you need to redo bed levelling if noozle is too close, use paper and bed screw

**Comment by Legendaire** [comment]
I used the leveling which used the probe.  I really, really like this feature of the printer.  Does this not work in this firmware?

**Comment by luc-github** [comment]
yes it is, but first you must do a manual bed leveling, autolevel is a fine tuning, references are differente between stock and repetier

**Comment by luc-github** [comment]
If no update I close topic
