### ISSUE TITLE
Bed and Extruder not heating from menu commands.

### ISSUE THREAD

**Issue by Chriss6181** [luc-github/Repetier-Firmware-0.92#184]
Hello I'm new and am not sure if this has been resolved, But I flashed my first generation Da Vinci 1.0 with the latest firmware and the bed and extruders does not heat up. Commands like auto bed level manual bed level and clean nozzle just sit while the screen displays heating. this was not an issue with .91 firmware or stock. Am I doing something wrong?

**Comment by luc-github** [comment]
Did you load default settings / or did a M502/M500 command ?

**Comment by Chriss6181** [comment]
Yes I did it still didn't work how ever I just refreshed and loaded the fail safes it took two trys but seems to be working. Thank you.

**Comment by luc-github** [comment]
you need to wait 20s after saving to EEPROM or any change before power down printer - saving EEPROM from memory to SD is done every 15s
