### ISSUE TITLE
EEPROM serial speed is not used - only 230400 is active (default one)

### ISSUE THREAD

**Issue by luc-github** [luc-github/Repetier-Firmware-0.92#189]
because of new virtual EEPROM -  Serial is set befaore EEPROM is loaded so default value is used

**Comment by tdelany** [comment]
Thank you, Luc.

**Comment by luc-github** [comment]
should be fixed by https://github.com/luc-github/Repetier-Firmware-0.92/commit/b64b0701c86de23144d0eced2db32fb3cb5161d5

**Comment by tdelany** [comment]
I'll check it out when I get home later.  I am back to work this week. :-(

**Comment by luc-github** [comment]
No problem - take your time - thanks

**Comment by TGMods** [comment]
Hi guys,
This morning I downloaded the latest master. I spent over an hour reflashing my Duo at various baud rates and was able to connect at whichever baud rate I had selected. I am now running my Duo at 250000.
Hope this helps

**Comment by luc-github** [comment]
Thanks a lot for your feed  back :smile:
