### ISSUE TITLE
please help so close but dont understand 

### ISSUE THREAD

**Issue by naothan** [luc-github/Repetier-Firmware-0.92#190]
In file included from Repetier.h:572:0,
                 from BedLeveling.cpp:107:
HAL.h: In static member function 'static void HAL::serialSetBaudrate(long int)':
HAL.h:684:14: error: 'class UARTClass' has no member named 'setInterruptPriority'
       Serial.setInterruptPriority(1);
              ^
Error compiling

**Comment by luc-github** [comment]
Looks like you are using IDE 1.5.8 to compile but as mentioned in readme:
`Use an arduino IDE supporting arduino DUE, 1.6.9 with Due 1.6.8 module from board manager.`

**Comment by luc-github** [comment]
latest version of repetier need 1.6+ IDE

**Comment by naothan** [comment]
have tried them all when i use a newer version the board isnt there (native usb port)

**Comment by luc-github** [comment]
yes you did not compile for Due but for Yun 
please check FAQ carefully : https://github.com/luc-github/Repetier-Firmware-0.92/issues?utf8=%E2%9C%93&q=is%3Aclosed+label%3AFAQ+

And you may review also this : https://github.com/luc-github/Repetier-Firmware-0.92/issues/175#issuecomment-239762985

**Comment by ironmann90** [comment]
I had the same issue earlier and it was because i was using 1.5.8 IDE. So i followed your steps on using a 1.6+ IDE. Now after flashing and loading everything (using 1.6.8DUE. I have 2 black bars and a msg pop up on my screen saying "USB Device not recognized"

**Comment by luc-github** [comment]
well different issue which means variant.cpp is not correct,
but same answer:
please check FAQ carefully : https://github.com/luc-github/Repetier-Firmware-0.92/issues?utf8=%E2%9C%93&q=is%3Aclosed+label%3AFAQ+

And you may review also this : https://github.com/luc-github/Repetier-Firmware-0.92/issues/175#issuecomment-239762985

**Comment by luc-github** [comment]
any update on this?

**Comment by luc-github** [comment]
if no update I close issue
