### ISSUE TITLE
Two black bars and computer will no longer recognize printer

### ISSUE THREAD

**Issue by Chromewrecker** [luc-github/Repetier-Firmware-0.92#210]
So I have had a sires or issues with both my printer and computer just got my computer back up and running and now I'm trying to get the printer back up but seem to have a issue. After arduino uploads the repetier host the printer does not do anything the black bars remain and the computer will get an error stating that the what is plugged in the USB port is not recognized. I have tried a couple of times same thing keeps happening. I can reset the printer and the message will go away until I try to upload the program again any thoughts out there

**Comment by Chromewrecker** [comment]
And no I can seem to get the printer to wipe it keeps saying USB device not recognized

**Comment by Chromewrecker** [comment]
Jumping j37 no longer seems to make a difference

**Comment by luc-github** [comment]
for the black bars please check FAQ
for the computer detection 2 possibilities:
1 - issue with computer port,  restart computer, try several ports
2 - the printer has hardware issue

**Comment by RootWizard** [comment]
@Chromewrecker Please see my comment in https://github.com/luc-github/Repetier-Firmware-0.92/issues/213  I had a similar issue and fixed it.

**Comment by luc-github** [comment]
if no update I close issue
