### ISSUE TITLE
Davinci 1.0a hangs at 79% not matter what I do.

### ISSUE THREAD

**Issue by TK1362** [luc-github/Repetier-Firmware-0.92#211]
I flashed my davinci 1.0a via the J37 two black bars and followed every tutorial in existence. Arduino 1.6.9 Due 1.6.8 copied the hardware folder ........gets to 79% and just stays there forever?

**Comment by luc-github** [comment]
did you checked the FAQ ?  I guess you are at 79% of verification and not upload,  https://github.com/luc-github/Repetier-Firmware-0.92/issues/185

**Comment by TK1362** [comment]
I did check the FAQ, I've tried different cables and ports but still same effect and the 79% is during the verify process

**Comment by luc-github** [comment]
so as mentioned in FAQ, disable verify process

**Comment by TK1362** [comment]
Thanks, I'll try it !!!

**Comment by TK1362** [comment]
I disabled the verify process in arduino and it completed but now the printer is not recognized?

**Comment by TK1362** [comment]
I tried it again and it worked! Thanks for the help luc..........you the man!

**Comment by luc-github** [comment]
good, happy printing 😄
