### ISSUE TITLE
Error: isPositionAllowed, Need Help.

### ISSUE THREAD

**Issue by bbozzi12** [luc-github/Repetier-Firmware-0.92#215]
i got my printer DaVinci 2.0 DUO flashed with repetier after alot of trouble, and when I connect to repetier host i can move the extruders around, in the bottom log when i try to manually move the print head it says: Error: isPositionAllowed
X: NAN Y: NAN Z: NAN E: NAN
any suggestions?

**Comment by luc-github** [comment]
I do not reproduce it :
![image](https://cloud.githubusercontent.com/assets/8822552/21712019/7677d614-d3f2-11e6-90d6-7745dd2fb9d5.png)


Did you do the M502/M500 command to properly setup virtual EEPROM ?

**Comment by bbozzi12** [comment]
no, how do i do that?

**Comment by bbozzi12** [comment]
i managed to fix it by loading my failsafe, i forgot to do it, and you were right. It is 4am here and I am not able to do anything right. Thanks for all the help man.

**Comment by luc-github** [comment]
yes loading failsafe and save them do the same 
Happy printing
