### ISSUE TITLE
How to use Extruder #2 ONLY in repetier?

### ISSUE THREAD

**Issue by bbozzi12** [luc-github/Repetier-Firmware-0.92#218]
i am using different filament colors, and i cant seem to find a way to use only the 2nd extruder.

**Comment by luc-github** [comment]
like any other printer: T0 is extruder 1 and T1 is extruder 2
https://github.com/luc-github/Repetier-Firmware-0.92/blob/master/src/ArduinoDUE/Repetier/Repetier.ino#L63-L64

So you need to configure your slicer to use T1, this is not specific to Davinci

**Comment by bbozzi12** [comment]
do i need to manually set that in the g-code?

**Comment by luc-github** [comment]
it depend of your slicer capabilities - some have macro some don't, some do not support more than one extruder, some automate the process

**Comment by bbozzi12** [comment]
how would i do it in cura?

**Comment by luc-github** [comment]
I do not use cura since a long time but you can check the settings I shared https://forum.voltivo.com/showthread.php?tid=8253&pid=2459#pid2459

**Comment by luc-github** [comment]
if no update I close topic

**Comment by Shawnh77** [comment]
Any chance you can share your settings again.  it appears that the forums have been shutdown due to spam.

**Comment by luc-github** [comment]
I do not have them anymore sorry - but I think cura was updated several times so I am not sure they would be still usable
