### ISSUE TITLE
Davinci 2.0 wont flash correctly

### ISSUE THREAD

**Issue by rcryguy** [luc-github/Repetier-Firmware-0.92#222]
I have added the files to the needed directories and get no errors when i compile the firmware.
when i upload the firmware, the backlight on the screen turns on but the black bars are still there and the computer says that the device isnt working properly. The device will connect/unconnect many times during this period. tried clearing and re flashing many times

**Comment by luc-github** [comment]
did you checked the FAQ ?

**Comment by rcryguy** [comment]
Yes, couldn't find anything to fix it. Everything seems to be correct

**Comment by luc-github** [comment]
let see
Where is your variant.cpp give me the full path
what is your OS ? 
what is your ide version and due module version from module manager ?

**Comment by rcryguy** [comment]
I'll get the path of the varient a bit later. Win 10 ide 1.8.0 due 1.6.8

**Comment by rcryguy** [comment]
C:\Program Files (x86)\Arduino\hardware\arduino\avr\variants is the folder it is in

to clear it up, the firmware is loaded to the printer but the printer doesnt boot up and is no longer recognized on the pc

**Comment by luc-github** [comment]
yes this location is wrong
as said in FAQ this is https://github.com/luc-github/Repetier-Firmware-0.92/issues/172
so read https://github.com/luc-github/Repetier-Firmware-0.92/issues/114 to find good location for variants.cpp there is a trick using preference to get hidden folder

**Comment by rcryguy** [comment]
C:\Users\rcryg\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.8\variants\arduino_due_x

opened it up and it was in here as well

**Comment by rcryguy** [comment]
copied the repetier files there just in case but still problem, excpet the pc sees it as arduino DUE now after flash

**Comment by luc-github** [comment]
yes this one is correct this is the place variant.cpp need to be modified

**Comment by rcryguy** [comment]
im going to reload arduino real quick, but still no luck

**Comment by luc-github** [comment]
did you verified you modifed the file and not copy to another location ?

**Comment by rcryguy** [comment]
Can you explain a bit? i replaced the variants.cpp with the one include in the repetier download

**Comment by luc-github** [comment]
Some people do a paste without checking the file is well replaced

One thing : you need to replace files with the ide closed, if ide is open changes may not be taken in account

**Comment by luc-github** [comment]
https://github.com/luc-github/Repetier-Firmware-0.92/issues/213#issuecomment-269435300

**Comment by rcryguy** [comment]
did that exact thing, i get this while compiling but it uploads anyway
![capture](https://cloud.githubusercontent.com/assets/25360194/22350987/8cca44e4-e3db-11e6-833b-712a95a5b764.PNG)

**Comment by luc-github** [comment]
yes this is a warning - it is not an issue

**Comment by rcryguy** [comment]
the rpinter still doesnt boot up on repetier, the backlight of the screen turns out but thats it. the black bars are still on the screen andwont respond to any commands in repetier host

**Comment by luc-github** [comment]
as originaly you did not do the right changes in right place you  may mess up something - I suggest you to uninstall the due module - uninstall arduino - wipe the board with jumper and restart process from scratch

**Comment by rcryguy** [comment]
just unistalled and reinstalled ide and due as long as a fresh download of repetier... still nothing

**Comment by luc-github** [comment]
and replaced variants.cpp of : C:\Users\rcryg\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.8\variants\arduino_due_x\variants.cpp ?

because black bars are wrong variants.cpp 100%

**Comment by rcryguy** [comment]
is variants.cpp supposed to be int the sketch to uload to the printer?

**Comment by luc-github** [comment]
sorry what process are you following to replace variants.cpp ? you confuse me

**Comment by rcryguy** [comment]
i copy the arduino15 folder to C:\Users\rcryg\AppData\Local and click replace on the popup warning me of the duplicate names

**Comment by rcryguy** [comment]
the folder i copy at first is from the firmware downoad

**Comment by luc-github** [comment]
and do you have this comment line 326 ?
  **// 125**
of 
C:\Users\rcryg\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.8\variants\arduino_due_x\variants.cpp

**Comment by Cannonized** [comment]
What version of arduino I had to modify a find line in the software using 1.6.5r2 I posted the fix as a comment in one of the posts I'll see if I can find it.

Sent from Yahoo Mail on Android 
 
  On Thu, Jan 26, 2017 at 1:44 AM, Luc<notifications@github.com> wrote:   
did you checked the FAQ ?

**Comment by rcryguy** [comment]
line 326 is highlighted
![capture](https://cloud.githubusercontent.com/assets/25360194/22352181/aa7438ce-e3e0-11e6-91c8-8fde64065756.PNG)

**Comment by rcryguy** [comment]
ide version 1.8.0 due version 1.6.8

**Comment by luc-github** [comment]
do you restart printer after flash is done ?

**Comment by rcryguy** [comment]
yes

**Comment by luc-github** [comment]
well I am dry - but my line 326 is not the one you highlighed
![image](https://cloud.githubusercontent.com/assets/8822552/22352386/3969453e-e41c-11e6-86bd-9ee249e79b5c.png)

**Comment by rcryguy** [comment]
so the black lines indicate that the variants.cpp is not correct?

**Comment by rcryguy** [comment]
just recopied so my line 326 lines up with yours

**Comment by rcryguy** [comment]
![capture](https://cloud.githubusercontent.com/assets/25360194/22352605/81f01682-e3e2-11e6-91ec-80df62c68d60.PNG) this is the output after upload

**Comment by rcryguy** [comment]
![capture](https://cloud.githubusercontent.com/assets/25360194/22360388/d18b0d50-e414-11e6-8b99-1cff977d53d8.PNG)
im trying arduino 1.5.8 now, and this is the error i get... maybe it will help find the problem? 
Any additional help is greatly appreciated because right now i have an expensive brick

**Comment by rcryguy** [comment]
Major breakthrough. I was able to take a bin file of the old firmware and upload it so I no longer have a brick, but can you create a bin file for this firmware?

**Comment by luc-github** [comment]
1.5.8 ide is not supported by current git version firmware, https://github.com/luc-github/Repetier-Firmware-0.92/releases/tag/v0.92.3.0 should work with 1.5.8

Yes if bin work - it confirm you do not follow the readme in someway and mess up with the code

**Comment by luc-github** [comment]
As no update I close issue
