### ISSUE TITLE
still black screen,

### ISSUE THREAD

**Issue by jepolqwerty** [luc-github/Repetier-Firmware-0.92#228]
Hi, 

    I followed all the steps correctly, and watch the tutorials, but still i get black bars in screen please help

**Comment by luc-github** [comment]
what is your printer?
did you read the FAQ?

**Comment by jepolqwerty** [comment]
may printer is da vinci 1.0A, yup i read the FAQ, i cannot find the FAQ#171
<https://github.com/luc-github/Repetier-Firmware-0.92/issues/201>, but
there is FAQ #172, but i followed that also

**Comment by jepolqwerty** [comment]
after the sending uploading in the printer, it disconnect and then it
continuously says that unrecognized USB

**Comment by jepolqwerty** [comment]
[image: Inline image 1]

after the uploading, it continuously says that Usb device not recognized.

Please help

**Comment by luc-github** [comment]
good catch typo issue
your issue is not correct update of variant.cpp

**Comment by jepolqwerty** [comment]
how do i fix it?

please instruct me.

**Comment by jepolqwerty** [comment]
im using arduino IDE 1.8.1

and arduino SAM board 1.6.11

**Comment by luc-github** [comment]
follow the readme exactly, and check Faq for details

using sam 1.6.11 is a proof you do not follow the readme, I never tested sam 1.6.11 so issue could come from there

**Comment by jepolqwerty** [comment]
i reset again the printer, change the sam to 1.6.8 copy the hardware from
AdditionalArduinoFiles, i still cant make it work

**Comment by luc-github** [comment]
what is the path of the variant.cpp you update?

**Comment by luc-github** [comment]
you solved your issue as mentioned here[#229] (https://github.com/luc-github/Repetier-Firmware-0.92/issues/229) ?
How did you do ?

**Comment by jepolqwerty** [comment]
I read the comments in other tutorials and they have the same problem as I
encounter. So what they did is to downgrade the IDE and install the older
version of repetier. I did it also and it works

**Comment by luc-github** [comment]
so which version of IDE did you used ?

**Comment by jepolqwerty** [comment]
I used the 1.5.8

**Comment by luc-github** [comment]
ok so you did not used the git version of fw but the 0.93.2 based

**Comment by jepolqwerty** [comment]
But im still playing the printer now. I think even though I made it. I
think the firmware is mess up. The light is not working in I cant made the
z axis to move up. Cant connect to the software. And I cant even load
filament.

**Comment by jepolqwerty** [comment]
There is already .93.2? Im trying to work before is the version 92.10
On Feb 27, 2017 11:03 PM, "Luc" <notifications@github.com> wrote:

ok so you did not used the git version of fw but the 0.93.2 based

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/luc-github/Repetier-Firmware-0.92/issues/228#issuecomment-282744965>,
or mute the thread

**Comment by luc-github** [comment]
I guess EEPROM is not correctly set - did you do the load fail safe seetings  ?
what fw version of FW are you using ?

**Comment by luc-github** [comment]
Sorry I mean 0.92.3 
0.92.10 do not compile with 1.5.8 so I do not get

**Comment by jepolqwerty** [comment]
I cant Remember, ill check it tomorrow. But it was version made late 2015

**Comment by luc-github** [comment]
if it was made in 2015 it is outdated I suggest you to use latest git version

**Comment by jepolqwerty** [comment]
I tried the 1.6.9 version and up and still the same, i cant made it work. i
dont know whats the problem. i followed all the instruction well, specially
need to copy the "arduino15 folder" inside the "additional folder" but
still i cant manage to install it. im starting to loose hope

**Comment by luc-github** [comment]
I have added more check on https://github.com/luc-github/Repetier-Firmware-0.92/issues/114

**Comment by jepolqwerty** [comment]
[image: Inline image 1]if your referring this, i cant find that version

**Comment by luc-github** [comment]
I do not see what image you linked

**Comment by jepolqwerty** [comment]
SAM version 1.6.2 BETA

**Comment by luc-github** [comment]
This is not the version I mention in read me , it is old and file location is different than latest version

**Comment by jepolqwerty** [comment]
that is in the picture in #114

**Comment by jepolqwerty** [comment]
i cant make the latest version worked, before it finished it disconnect.
the older version i mange to send it to the printer, but the old version is
messed up. do you have any older version? newer than
https://github.com/luc-github/Repetier-Firmware-0.92/releases/tag/v0.92.3

**Comment by jepolqwerty** [comment]
but older version of this,
https://github.com/luc-github/Repetier-Firmware-0.92/releases/tag/v0.92.3.0

**Comment by luc-github** [comment]
the latest one is this one:
https://github.com/luc-github/Repetier-Firmware-0.92/archive/master.zip

**Comment by jepolqwerty** [comment]
my printer now is working, thanks in reviewing all the video tutotials

i have another problem now, i cant used simplify 3d in the printer

**Comment by luc-github** [comment]
Good - may I know what was the issue ? 
what step was different  with read me or FAQ ?

**Comment by jepolqwerty** [comment]
i still cant manage to make latest version work. i used the older version,
the reason why the firmware send to my printer is messed up, is because i
did not select the J37 port,

i manage to connect the printer to repetier host but i cant send gcode to
the printer, do you have settings?  can you share it to me?

**Comment by luc-github** [comment]
Did you used the settings I shared ? https://github.com/luc-github/Repetier-Firmware-0.92/issues/229#issuecomment-282775061

what you mean by send GCODE, when you press home in manual tab is it not working ?

**Comment by jepolqwerty** [comment]
I cant control the printer using the repitier host and when I hit print
nothing is happen to the printer its not even heatingqup

**Comment by luc-github** [comment]
Did you load failsafe settings from printer like wrote in readme?
Or send M502 M500 from repetier host?
