### ISSUE TITLE
cant connect to slicing software

### ISSUE THREAD

**Issue by jepolqwerty** [luc-github/Repetier-Firmware-0.92#229]
Hi,
   I managed to flash the firmware its just that now i cant connect to the printer, in simplify3d it can find, but cant connect, in xyz ware, totally cant find

**Comment by luc-github** [comment]
simplify3d can connect repetier - check baud rate - uncheck wait for start and be sure hardware flow control is  checked

 xyz ware is not working of course - it is no more xyz firmware - but all hosts that can connect with repetier/marlin FW can connect

**Comment by jepolqwerty** [comment]
Even in repetier host. I cant connect. The printer keeps rejecting the
connection. How about in the printer do I need to configure anything
On Feb 27, 2017 10:34 PM, "Luc" <notifications@github.com> wrote:

simplify3d can connect repetier - check baud rate - uncheck wait for start
and be sure hardware flow control is checked

xyz ware is not working of course - it is no more xyz firmware - but all
hosts that can connect with repetier/marlin FW can connect

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/luc-github/Repetier-Firmware-0.92/issues/229#issuecomment-282736752>,
or mute the thread

**Comment by luc-github** [comment]
here my settings - I close issue as not fw related
![image](https://cloud.githubusercontent.com/assets/8822552/23370110/95c2459c-fd4e-11e6-8867-edeca1509bc9.png)

**Comment by jepolqwerty** [comment]
Thank you, but even though i manage to connect the printer. i cant use it,
i need to reflash the printer
