### ISSUE TITLE
Davinci 2.0 stopped working??

### ISSUE THREAD

**Issue by bbozzi12** [luc-github/Repetier-Firmware-0.92#234]
i was in the middle of printing and the front display just turned off. I thought it was a software issue so i tried re flashing the printer and now none of the lights are turning on or the front display. What do I do?

**Comment by bbozzi12** [comment]
i just tried uploading repetier onto the printer and nothing happened, the red light on the board is still on but the front display and lights are still off.

**Comment by luc-github** [comment]
looks more hardware issue to me, like a short or hardware failure

did you wipe with jumper? what does screen display ?

**Comment by luc-github** [comment]
looks more hardware issue to me, like a short or hardware failure

did you wipe with jumper before reflashing?

**Comment by bbozzi12** [comment]
i wiped with the jumper and everything turned off

**Comment by bbozzi12** [comment]
originally when the front display first went off, i stopped the print and it wouldnt let me control the heaters anymore, so i turned the printer off and back on and it still wouldnt let me control the heaters. So i wiped the printer and all the lights went off.

**Comment by luc-github** [comment]
As wrote before looks like an hardware problem, if reflashing did not helped it is confirmed

**Comment by bbozzi12** [comment]
do you have any idea what hardware it could be

**Comment by luc-github** [comment]
nope sorry, looks like you can detect usb and flash so should not be MCU issue, I would guess for a short, unplug all and retry flashing ang check if serial output send something
if ok then connect back screen to see if display is ok, then others connectors one by one

**Comment by bbozzi12** [comment]
thanks anyways, this is my 3rd davinci, they always give me issues

**Comment by luc-github** [comment]
davinci is very fragile, wires are easy to break, especialy new generation

I cross my fingers, my 2.0 has only one loose connector issue since I got it

**Comment by luc-github** [comment]
I close issue as Hardware issue
