### ISSUE TITLE
R1 Advice given in #104 is misleading

### ISSUE THREAD

**Issue by sdp8483** [luc-github/Repetier-Firmware-0.92#237]
I installed a new hotend on my DaVinci 1.0A and that meant a new thermistor.

The advice given in #104 for a possible solution to using a different thermistor then the stock was to replace resistors R29=1K and R27=4.7K to match those expected by repetier when using a generic thermistor table, specifically R1=0K and R2=4.7K.

The value given for R1 is misleading and suggests to replace R29 with a 0 ohm resistor it should instead suggest that R1 is open or infinite resistance not a short to ground.

**Comment by luc-github** [comment]
Good catch, it is a mistake - it is corrected - thanks for pointing this
