### ISSUE TITLE
Button response slow in print file menu.

### ISSUE THREAD

**Issue by jamskate** [luc-github/Repetier-Firmware-0.92#240]
Has anyone experienced an issue that the menu buttons work fine in all menus except the print file menu?  as soon as I open the print file menu I have to hit the buttons repeatedly or hold them longer to scroll down thru the choices.   I have Repetier loaded on a 1.0A and a 2.0A and I only have this problem on my 1.0.

**Comment by luc-github** [comment]
could be same as : https://github.com/luc-github/Repetier-Firmware-0.92/issues/186
and if it is happening on one printer and not another - should be an SD card issue

**Comment by luc-github** [comment]
Any update on this ?

**Comment by jamskate** [comment]
Sorry.  Yes, reformatted my SD card and it fixed the problem.

**Comment by luc-github** [comment]
ok thanks, I close issue then
