### ISSUE TITLE
DA Vinci Jr. Port Showing bossac board help to install firmare

### ISSUE THREAD

**Issue by prahalad1224** [luc-github/Repetier-Firmware-0.92#244]

**Comment by luc-github** [comment]
sorry what the issue ? 
there is no repetier FW for JR currently - the MCU is not supported

**Comment by luc-github** [comment]
bossac port is here : https://github.com/luc-github/BOSSA/tree/arduino
but still on going - need to use SAM-BA 2.16 for the moment
