### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by demotte9** [luc-github/Repetier-Firmware-0.92#258]
Hello, i made all the step to flash my da vinci. The last command on my arduino board is CPU reset. Anyway, there is always the two black lines on the printer and my computer doensn't reconize the printer now... I try 3 times but always the same problem.. Please help !

![image](https://user-images.githubusercontent.com/29837584/27770422-cccf7364-5f3e-11e7-8bd6-b1a8b201d066.png)

![image](https://user-images.githubusercontent.com/29837584/27770410-aff4e788-5f3e-11e7-91b9-97e719694bd2.png)

**Comment by luc-github** [comment]
it is typical issue : https://github.com/luc-github/Repetier-Firmware-0.92/issues/172

**Comment by luc-github** [comment]
any update ?

**Comment by luc-github** [comment]
Ok I close issue if no update

**Comment by demotte9** [comment]
yes, i try this weekend but it doesn't work, i will make some update with
print screen this week.

Regards,

Antoine

2017-07-16 22:56 GMT+02:00 Luc <notifications@github.com>:
