### ISSUE TITLE
Bed too high

### ISSUE THREAD

**Issue by zipippino** [luc-github/Repetier-Firmware-0.92#267]
Hi, i have a DaVinci 1.0A
I have succesfully installed the repetier firmware but while printing here the error comes. The extruder is too much close to the bed and so the extruder crushes on the printed plastic and makes a disaster. That's because the bed is too much elevated, i think. How could i solve?

![settings1](http://i.imgur.com/tS6FSwO.png)
![settings2](http://i.imgur.com/fsqgGh4.png)
![settings3](http://i.imgur.com/mLbCrzR.png)

**Comment by luc-github** [comment]
you must do bed leveling after flashing - did you do it ?

**Comment by zipippino** [comment]
Auto leveling directly from the printer? Done, but still nothing

Sent by iPhone   
Francesco Buccoliero aka zipippino
Inforge.net Staff & Graphic Designer

**Comment by luc-github** [comment]
Manual bed leveling using screw and paper sheet - autoleveling is just a fine tune feature

**Comment by zipippino** [comment]
Do you have a video or textual guide to do that?

Sent by iPhone   
Francesco Buccoliero aka zipippino
Inforge.net Staff & Graphic Designer

**Comment by luc-github** [comment]
the manual bed leveling wizard is available in the printer menu 

there are toons of youtube video for this and several post for Davinci and even more for others printers - just google it and you will get them -  this is not specific to Davinci

**Comment by luc-github** [comment]
Close issue as no update
