### ISSUE TITLE
Connection failure when printer swith on after operating system loads

### ISSUE THREAD

**Issue by Hawat3000** [luc-github/Repetier-Firmware-0.92#272]
Hello
I have a strange problem with my DaVinci 1.0 and the Repetier firmware. If I power on the printer before the operating system has loaded everything works fine, but if I connect the printer after the system starts I always have a error in Repetier-Host, cant connect to the COM port. I have the same problem if I restart the printer (power off and on) when I am working in the operating system).
I have tested it in Windows 7 x64 and Windows 10 x64 (in the same computer)
Any ideas?

**Comment by luc-github** [comment]
No, never got such issue sorry

**Comment by Hawat3000** [comment]
Thank you for your response, and by the way for the firmware ;)
It is very strange. The com port is the same if a switch on the printer before or after. But the behavior is different.

**Comment by luc-github** [comment]
did you patched the USBCore.cpp ?

**Comment by Hawat3000** [comment]
If you refer to copy the file from:
X:\Repetier-Firmware-0.92-master\src\ArduinoDUE\AdditionalArduinoFiles\Arduino - 1.8.0 -Due 1.6.8\Arduino15\packages\arduino\hardware\sam\1.6.8\cores\arduino\USB
To:
C:\Users\XXX\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.8\cores\arduino\USB

Yes I have done.
I just have repeated the process two times and I have the same problem.
I know that is not a great problem (because it works if you connect the printer before) but now it is curiosity

![image](https://user-images.githubusercontent.com/25452784/33382017-e69e538a-d51f-11e7-8190-4099de2bfc0b.png)

The icon show that the printer is connected but a messagebox appears telling conection error and the printer not responds.

**Comment by luc-github** [comment]
To be honest davinci USB is not the best because Due port is native port and can be peaky
Also I saw also repetier host have some com issue with windows time to time but not systematic like you

2 things you can try : 
1 - update repetier host yours is 1.06 current is 2.05 
2 - try without USBCore patch : unistall Due 1.8 from board manager then install again, do not forget to update variants.cpp (this one is mandatory),  the usbcore patch allow safer communication avoiding dead loop and printer reset if serial is disconnected when open (pc go standby, cable unpluged, etc..) this patch may disturb your com port, I am not confident about this but it worth to try ^_^

Hope it helps

**Comment by Hawat3000** [comment]
Without the usbcore patch the printer still not connect but when you click on connect or disconnect the printer reboot
:-O

**Comment by luc-github** [comment]
yes that is why I wrote it ^_^
it looks like something lock your com, you do not use hub ?

**Comment by Hawat3000** [comment]
I have tested it with different Repetier Host, with a usb hub and  without a usb hub with the same behavior...
Can you tell me a simple "hello" to try with the Arduino IDE serial port console?

Thank you

**Comment by luc-github** [comment]
it is serial communication emulation so must not use hub on this com
check in arduino terminal if you can see the printer message
also be sure repetier host has same baud rate as printer

no sure what you mean by simple "hello"
Is it that ? https://www.arduino.cc/en/Serial/Write

**Comment by Hawat3000** [comment]
Sorry I have explain wrong. I mean some kind of hello command in the Arduino serial monitor to get some kind of message from the printer.

**Comment by luc-github** [comment]
When printer wait for command it send "wait" message constantly

in serial monitor select cr/lf 
You can send M115 to get printer info, M105 for temperature M20 for file list , M205 for EEPROM output
check list here : https://github.com/luc-github/Repetier-Firmware-0.92/blob/master/src/ArduinoDUE/Repetier/Repetier.ino

**Comment by luc-github** [comment]
any update ?

**Comment by Hawat3000** [comment]
Same behavior, if the printer is connected when operating system starts I see the wait command in the Arduino Serial monitor. If I switch off the printer and switch on again the wait command disappear

**Comment by luc-github** [comment]
after switch off printer you need to close then open again Arduino Serial monitor because connection is closed. Then you should see wait command.

**Comment by Hawat3000** [comment]
I have closed and restarted the Arduino and no wait command....

**Comment by luc-github** [comment]
strange - what about usb unplug cable then open arduino terminal ?

**Comment by Hawat3000** [comment]
same behavior....

**Comment by luc-github** [comment]
I never had such issue before but gave a try today and was able to reproduce it
I have just updated from win7  to windows 10 a week ago not sure it is linked 

Arduino terminal says port is busy!!! and repetier host cannot connect to printer!!!

So I have uninstalled due drivers and restarted computer as requested  (printer is not connected) - then I have connected printer 
Arduino terminal show nothing when connected to printer 
But now Repetier can connect 

Not sure where the issue come from but I suspect the due module or the drivers

I set this as bug and will try different modules to see if it is solved with latest or if it is a regression issue and check old ones

**Comment by luc-github** [comment]
After updating to Due 1.6.11 and of course updating variant.cpp /USBCore.cpp I cannot reproduce anymore 

Can you try and feedback ?

**Comment by Hawat3000** [comment]
When you says updating to Due 1.6.11 do you refer to Arduino 1.6.11 or card
version in Arduino cards management?

El 11 dic. 2017 9:55 p. m., "Luc" <notifications@github.com> escribió:

After updating to Due 1.6.11 and of course updating variant.cpp
/USBCore.cpp I cannot reproduce anymore

Can you try and feedback ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/luc-github/Repetier-Firmware-0.92/issues/272#issuecomment-350855132>,
or mute the thread

**Comment by luc-github** [comment]
due board in board manager, my arduino is still 1.8.4

**Comment by Hawat3000** [comment]
Now I have a big problem.
I have done what you told me, but now the 3d printer has bars in the screen and Windows not recognize the printer.
The usb connects and disconnects constantly so I cant upload the firmware again.

**Comment by luc-github** [comment]
that means wrong location for variant.cpp and USBCore.cpp - you have to use jumper to reset

**Comment by Hawat3000** [comment]
I am trying to reset via jumper (i did it two years ago), I am trying now but it doesn´t work.
Please tell me if i am making something wrong.
1) with printer power on (without usb) jumper pins JP1 during 5 seconds.
2) switch off power and switch on again
3) My black bars continues on screen and when i connect it to the pc, the usb connects and disconnects

**Comment by Hawat3000** [comment]
Ok, now it is reseted

**Comment by luc-github** [comment]
JP1  so you have a Davinci 1.0 then ? the one with the normal SD card not micro one
I have Duo with same board base and this one is more robust than new generation so no worry there is few chance you briked it

**Comment by Hawat3000** [comment]
Some more tests:
- Arduino 1.8.0 and  Due 1.6.11 (updated from 1.6.8) in windows 7, resut: the same behavior
- Arduino 1.8.4 and  Due 1.6.11, fresh install and windows 10, resut: the same behavior

These are my Arduino Due drivers:
![image](https://user-images.githubusercontent.com/25452784/33883972-295291aa-df3e-11e7-8608-84e8e3574189.png)

**Comment by luc-github** [comment]
I have same drivers, Arduino 1.8.4 and Due 1.6.11 on windows 10

PC is on - printer is off and disconnected
Printer On then connect : Arduino Serial terminal and repetier host are OK ( can see wait msg and connect)

Power Off Printer still connected - Power On printer : Arduino Serial terminal and repetier host are OK ( can see wait msg and connect)

I am not sure what is the problem as now I cannot reproduce it anymore ...

**Comment by luc-github** [comment]
Any update ?

**Comment by Hawat3000** [comment]
Hello Luc
I just have tested it in a third computer and the problem stops. On this PC
you can switch off and switch on the 3d Printer without problem.

2018-01-11 8:51 GMT+01:00 Luc <notifications@github.com>:

**Comment by luc-github** [comment]
so it is confirmed it is on PC side - thank you for the feedback, I close issue then
