### ISSUE TITLE
USB switch mid install?

### ISSUE THREAD

**Issue by bazookaboom** [luc-github/Repetier-Firmware-0.92#275]
My computer kept saying USB not recognized in the middle of the upload what should I do because it wouldn't install as a port after that.

**Comment by luc-github** [comment]
During upload process it happen that USB com change under windows, so upload say no port COM as  it has changed  - just select new COM and retry upload no need to do hardware reset

**Comment by luc-github** [comment]
did you managed the issue ?

**Comment by luc-github** [comment]
I close as no update

**Comment by bazookaboom** [comment]
Yes sorry ty. I fixed it by using a video that on how to set the program to
print, then pause it, then turn off the motor, then manually move the tray
and the extruder to proper home position then home the printer.
