### ISSUE TITLE
Bed axis and X and Y calibration problems

### ISSUE THREAD

**Issue by bazookaboom** [luc-github/Repetier-Firmware-0.92#277]
I tried uploading the new Repetier firmware and I cant calibrate the printer head because the software doesnt know where the center of the printer is, and it keeps colliding with the walls and the printer bed. Can anyone tell me what I need to do to fix this.

**Comment by luc-github** [comment]
Which software ?
What settings for the bed did you used ? 
Which printer ?

**Comment by bazookaboom** [comment]
Repetier 0.92 davinci 1.0

**Comment by luc-github** [comment]
I do not use repetier but have toons of youtube video to give settings for this https://www.youtube.com/watch?v=4sg3V7TwOR0

**Comment by luc-github** [comment]
I close as no update
