### ISSUE TITLE
How to reflash after initial flasing

### ISSUE THREAD

**Issue by JimGwynn** [luc-github/Repetier-Firmware-0.92#278]
The readme states that steps 1&2 are not required after the first flash. How do you reflash? Arduino IDE sees the printer port but cannot upload the firmeare?

**Comment by luc-github** [comment]
yes arduino ide should be able to flash without using the jumper by just doing upload.

if cannot flash there is an issue : corrupted fw or wrong variant.cpp, many root cause  - in that case try using the jumper wipe all and get clean board then upload should work

**Comment by luc-github** [comment]
I close because  no update
