### ISSUE TITLE
G10 and G11 commands and M209, M355, M600, M360

### ISSUE THREAD

**Issue by luc-github** [luc-github/Repetier-Firmware-0.92#32]
these commands are now available in repetier, need to importe them

**Comment by luc-github** [comment]
https://github.com/repetier/Repetier-Firmware/commit/54298f82172c04ad39a24c73263982ebd8de1650

**Comment by Doudou14** [comment]
If I can, I do it in a few hours

**Comment by luc-github** [comment]
Would be great - I am little bit busy this week 
But take your time - there is no hurry so far

**Comment by luc-github** [comment]
Sorry very busy - https://github.com/luc-github/Repetier-Firmware-0.92/pull/35
I keep it in tracker

**Comment by luc-github** [comment]
M360 done : https://github.com/luc-github/Repetier-Firmware-0.92/commit/d9bbcf3c5b4201d9d19ccc0ff429794e6def0f8e
M355 done: https://github.com/luc-github/Repetier-Firmware-0.92/commit/d46b1e12f31ff44711860a98bce4e3d371d70706

**Comment by luc-github** [comment]
All done - M600 is slightly modified as buggy and I think it is more clear to use Load/Unload menu
https://github.com/luc-github/Repetier-Firmware-0.92/commit/78a45d94b1f597cdf2deedb59553d9a3b04077e7
