### ISSUE TITLE
USBCore.cpp

### ISSUE THREAD

**Issue by Doudou14** [luc-github/Repetier-Firmware-0.92#36]
Must you use this file?
What is it?

Thank :)

**Comment by luc-github** [comment]
it is to solve the USB serial bug that freeze printer :
https://github.com/luc-github/Repetier-Firmware/issues/43

**Comment by luc-github** [comment]
It is arduino issue actually

**Comment by Doudou14** [comment]
Ah okay, it's cool ! Thank :)

**Comment by luc-github** [comment]
de rien :smile:
