### ISSUE TITLE
Simplify 3D stop randomly to print then resume after few seconds

### ISSUE THREAD

**Issue by luc-github** [luc-github/Repetier-Firmware-0.92#38]
When this happen on serial monitor I see bunch of "wait" commands and on LCD the buffer decreasing, Can navigate in printer menu when this happen - so printer is not frozen and this does not trigger the watchdog
After few seconds print resume, I did not observed any crash neiter print failure but, seems weird.
This never happened with repetier host so far
I have set same setting for communication in S3D than for repetier
202 cache / Hw flow control /  baud rate 230400

not sure how to address this

**Comment by luc-github** [comment]
Move to 63 in cache, the default value, and remove the number ack in FW. as it always showed "ok 0" in simplify when the command expected by S3D is "ok"
 this time the printer stop at heating bed but do not send the  heat extruder in gcode script. got a bench of "wait" and even one "wai"
Because S3D do not use the command control of repetier it may be a usb connection issue, so I increase the retry in usbcore of the usb modification from 10K to 100K
at it is random need to test 
next is to change usb cable to one with ferrite to limit signal polution

**Comment by oscahie** [comment]
Maybe try increasing the 'Communication timeout' value from 10 to 20?

**Comment by luc-github** [comment]
Well I observed that buffer is empty when waiting - so a timeout of 20 second should not change anything
I did not printed today so cannot see yet if the modification of usb patch changed something - at least I did not see after I did it but need to be in front of printer on good moment to so need more test - I have a 10h+ print under preparation, I should launch it Sunday late afternoon, so I will be able to check if happen again or not

**Comment by garry572** [comment]
I had issues with the USB connection, on any of the USB3 ports I always had communication errors, moving back to the USB 2 ports the problems dissappeared

**Comment by luc-github** [comment]
Well it is connected to "old" laptop (4 years) not having USB3 but port connector is little bit loose so I guess usb connection is not optimale

**Comment by luc-github** [comment]
I do not use direct connection anymore but flashair SDCard and SD Card Printing and no issue
Anyway I removed the USBCore.cpp patch for the new 1.6.0 ide, so it give oportunity to test and see if it is part of the root cause 
Feedbacks are welcome as usual

**Comment by leghk** [comment]
I just compiled and installed a couple of days ago with 1.6.0 (after the USBCore.cpp removal) and this pause bug happens to me two or three times per hour of printing. The communication log shows:

__WARNING: Firmware unresponsive. Attempting to force continue.,,__

That is during USB printing from a Mac Mini .

**Comment by luc-github** [comment]
1.6.0 has some USB issue https://github.com/luc-github/Repetier-Firmware-0.92/issues/51
better use 1.5.8 right now

**Comment by luc-github** [comment]
I read on some forum that increasing the buffer on Simplify helped but I do not think it is the problem and the solution,  because computer is faster than Davinci board, GCODE time generation does not explain why printer can be stuck waiting command for several seconds.

I have recently sync the code from 0.92.3 and set the echo command back to 1 like in repetier in case of S3D use this as a check, and should help to see what command are lost

**Comment by gamecompiler** [comment]
Id had have this problem too, id  increased the buffer to 2024.
Works great now.

**Comment by luc-github** [comment]
Buffer from S3D right ?

interesting, I have seen other people also increasing buffer saying was better but did not tested 

this is good to know - thanks a lot for sharing
let see if anyone can also feedback this is the magic number, so I can close issue -  appreciate your help

**Comment by gamecompiler** [comment]
Yes, and id had have the same problems in Repetier and S3D.
2024 had fix the issue

**Comment by luc-github** [comment]
Repetier also ? wow first time I heard about this

**Comment by pallemar** [comment]
The problem may also be becourse the slicer put in a wait time, to allow the filament to cool, before continuing the printing, if you see some video about how slicer works, you will see it explained ;)

**Comment by luc-github** [comment]
During my tests the issue happen in middle of layer, not at the end when the slic3r may do some delay - also my layer was a big one - so at tha time each layer take more time than minimum time set in slicer - 
I am pretty confident it is  communication issue - reading at the thread I now realize that I forget to test at 115200 baud rate to check if it could solve the problem...

**Comment by pallemar** [comment]
You are right the problem should not come in big prints :)

**Comment by thevisad** [comment]
I made all the changes here and am seeing the same issue still present on the machine. The printer is pausing, buffer dropping to 0 and failing to proceed. One comment in the robo3d forums indicates that they upped the timeout to 20s which solved the problem. I will give this an attempt later tonight, I can pop out the SD card, but I prefer to print via USB. I am using a 2012 iMac with the software.

**Comment by luc-github** [comment]
Ok thanks for your feedback, waiting for your results

**Comment by efespilsen03** [comment]
hello Luc, i am boolat :) 
My setting:
baud rate: 250000
serial cache size: 2024
Wait for startup command: enable

no problem for 5 days!
it runs like a Ferrari!
thank you for your help LUC :+1:

**Comment by luc-github** [comment]
good to know - thanks for sharing

what version of S3D are you using with these settings  2.2 or 3.0 ?

**Comment by efespilsen03** [comment]
use 2.2 simplify3d 
Windows 7

**Comment by luc-github** [comment]
Ok thanks a lot so I close issue 
again thanks for your feedback

**Comment by luc-github** [comment]
seems there is a fix for this behavior related to native port :
github.com/repetier/Repetier-Firmware/pull/425

Will add it later

**Comment by luc-github** [comment]
Release 0.92.6 is done but need to see if fix is implemented or still testing

**Comment by luc-github** [comment]
Fix seems in 0.92.6, I created the test branch and will start the sync soon

**Comment by thomastech** [comment]
That is great news.
- Thomas

**Comment by luc-github** [comment]
0.92.6-sync branch is available for testing

**Comment by Cannonized** [comment]
I'm having the same issue. Buffer dropping to zero where is the fix? I've been up all night and I'm cranky I apologize for the attitude at the moment. Grrrr printing with DaVinci 1.0!!!

**Comment by luc-github** [comment]
did you tried the 0.92.6-sync branch ?
https://github.com/luc-github/Repetier-Firmware-0.92/tree/0.92.6-sync

**Comment by Cannonized** [comment]
Thanks luc.  I did find it. I apologize I'm not at my finest quality right now.

**Comment by luc-github** [comment]
additionally if you have a 1.0 it is easy to put and extender or a wifi card to print from wifi
printing from host is always subject to possible errors - that is why XYZ print from SDcard on stock FW

**Comment by Cannonized** [comment]
How do I go about loading to the SD card without removing from the back of the printer? Do I just name my file as sample## then unplug and hit print from menu? 

Also I assume I need the new src folder from the sync branch.?

**Comment by luc-github** [comment]
Yes to plug in an extender or wifi SDCard you need to remove back - but after no need anymore
Repetier list content of file on SDCard no need to give sample## as name just extension is necessary
You even can launch from repetier host also from SDCard management menu

Yes same as master but from sync branch

**Comment by luc-github** [comment]
here an example of extender :
http://www.ebay.com.au/itm/Extension-SD-SDHC-Card-Reader-Cable-Cord-Adapter-for-GPS-DVD-LED-Screen-/111183763834?hash=item19e311997a

and here the wificard: http://www.miniinthebox.com/fr/flash-toshiba-8gb-sans-fil-de-l-air-carte-memoire-sdhc_p1679330.html?currency=EUR&litb_from=paid_adwords_shopping

I only use flash air on all my printers - no usb connection - and wifi copy is very fast

**Comment by Cannonized** [comment]
OK so do I have to the variants.cpp exchange again or just upload the new repetier.ino file?
I'll look into the cd card mod later. Try uploading from the host but I think I have to keep my laptop connected to keep it printing maybe that will change with the new fw

Sent from Yahoo Mail on Android 
 
  On Fri, Feb 5, 2016 at 1:34 PM, Luc<notifications@github.com> wrote:   
here an example of extender :
http://www.ebay.com.au/itm/Extension-SD-SDHC-Card-Reader-Cable-Cord-Adapter-for-GPS-DVD-LED-Screen-/111183763834?hash=item19e311997a

and here the wificard: http://www.miniinthebox.com/fr/flash-toshiba-8gb-sans-fil-de-l-air-carte-memoire-sdhc_p1679330.html?currency=EUR&litb_from=paid_adwords_shopping

I only use flash air on all my printers - no usb connection - and wifi copy is very fast

**Comment by luc-github** [comment]
variant.cpp and usbcore.cpp are for your arduino IDE installation - if you still use same not need to update again as previous one are still there - but if you do new Arduino IDE installation you need to apply the variant.cpp and usbcore.cpp

Uploading from host is working but it take ages when using wifi or direct copy to SDCard and then plug SDCard to extender is immediate

**Comment by Cannonized** [comment]
OK I have the new sync loaded. Print is readying itself. I will update either way to see if the fix takes. 90% of my prints at this point  for this project are 8+ hrs. 

Sent from Yahoo Mail on Android 
 
  On Fri, Feb 5, 2016 at 1:46 PM, Luc<notifications@github.com> wrote:   
variant.cpp and usbcore.cpp are for your arduino IDE installation - if you still use same not need to update again as previous one are still there - but if you do new Arduino IDE installation you need to apply the variant.cpp and usbcore.cpp

Uploading from host is working but it take ages when using wifi or direct copy to SDCard and then plug SDCard to extender is immediate

**Comment by Cannonized** [comment]
Still having issues with the buffer communication from the host. Managed to get it to print for 3 and a half hours before the buffer issue became a problem and the printer stopped. Uploading to the SD card. Now while the code is running from the sd card can I remove the computer to use it elsewhere or do I need it attached still. Slightly nervous on unplugging it from the printer.

Sent from Yahoo Mail on Android 
 
  On Fri, Feb 5, 2016 at 1:57 PM, clifford cannon<cliffordcannon101@yahoo.com> wrote:   OK I have the new sync loaded. Print is readying itself. I will update either way to see if the fix takes. 90% of my prints at this point  for this project are 8+ hrs. 

Sent from Yahoo Mail on Android 
 
  On Fri, Feb 5, 2016 at 1:46 PM, Luc<notifications@github.com> wrote:   
variant.cpp and usbcore.cpp are for your arduino IDE installation - if you still use same not need to update again as previous one are still there - but if you do new Arduino IDE installation you need to apply the variant.cpp and usbcore.cpp

Uploading from host is working but it take ages when using wifi or direct copy to SDCard and then plug SDCard to extender is immediate

**Comment by luc-github** [comment]
you do not need computer connect when printing from SDCard
So you mean the new code did not fix the issue ? that is bad

**Comment by Cannonized** [comment]
Didn't seem to fix it for me. I tried a different port on my laptop got almost 4 hours out of it this time. Going to pick up a better USB cable when I can see if that makes a difference so far on the SD print the buffer is a solid 32 which is nice to see for a change. At least I've somewhat got it back to stock functionality where I can load the file and let my kids watch movies as we await dad's latest creation.

Sent from Yahoo Mail on Android 
 
  On Fri, Feb 5, 2016 at 9:58 PM, Luc<notifications@github.com> wrote:   
you do not need computer connect when printing from SDCard
So you mean the new code did not fix the issue ? that is bad

**Comment by luc-github** [comment]
well USB connection need a good cable, no electric appliance around, be sure PC do not go in sleep mode, a lot of factor can bring noise on it and make printing fail

**Comment by luc-github** [comment]
I will get back my printer on March (if no issue) so cannot test right now but will check why fix do not work

**Comment by thevisad** [comment]
I had an issue on my Mac (and only the mac) with simplify3d and the printer
stopping constantly. As soon as I switched over to a PC I stopped having
the printer issues. The printer on the Mac acted exactly like the comments
in here. I tried the other solutions offered but none worked. The only work
around on the Mac was to print from the SD card.

**Comment by Cannonized** [comment]
I'm on pc using slic3r from the host. SD printing works amazing. Was finally able to get the print with only a few strings from badly generated supports but that's another issue. Now to figure out how to program in a colour change part way through. I liked the idea of printing from the host so I could use all the filament pause it when there was about 10cm left switch colours and resume. At least I'm printing again and can finally get the parts stage off the back burner for this project.

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 6, 2016 at 12:32 PM, thevisad<notifications@github.com> wrote:   I had an issue on my Mac (and only the mac) with simplify3d and the printer
stopping constantly. As soon as I switched over to a PC I stopped having
the printer issues. The printer on the Mac acted exactly like the comments
in here. I tried the other solutions offered but none worked. The only work
around on the Mac was to print from the SD card.

**Comment by luc-github** [comment]
@Cannonized you can pause when printing from SD

**Comment by Cannonized** [comment]
The moment I unplug the computer from the printer it just resets. I can't see the SD file in the print file selection on the printer just from host. Am I doing something wrong?

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 6, 2016 at 12:51 PM, Luc<notifications@github.com> wrote:   
@Cannonized you can pause when printing from SD

**Comment by luc-github** [comment]
Did you applied the usbcore.cpp from my github ? this prevent printer reset when usb connection is active and stopped not properly

does your file has an extension ? if no extension or extension is bin or dat file is not displayed on lcd

**Comment by Cannonized** [comment]
Oh maybe that's what I'm doing wrong is not saving.gcode. I didn't use USB core.cpp uploaded with arduino 1.6.5 r2, deleted the core call in one of the libraries. That's all in another thread though.

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 6, 2016 at 1:42 PM, Luc<notifications@github.com> wrote:   
Did you applied the usbcore.cpp from my github ? this prevent printer reset when usb connection is active and stopped not properly

does your file has an extension ? if no extension or extension is bin or dat file is not displayed on lcd

**Comment by Cannonized** [comment]
None of the .guide files will print direct from the printer. It just shutters the print head and resets. Oh well at least printing with the computer attached and the file loaded on the SD card it works. 

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 6, 2016 at 1:45 PM, clifford cannon<cliffordcannon101@yahoo.com> wrote:   Oh maybe that's what I'm doing wrong is not saving.gcode. I didn't use USB core.cpp uploaded with arduino 1.6.5 r2, deleted the core call in one of the libraries. That's all in another thread though.

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 6, 2016 at 1:42 PM, Luc<notifications@github.com> wrote:   
Did you applied the usbcore.cpp from my github ? this prevent printer reset when usb connection is active and stopped not properly

does your file has an extension ? if no extension or extension is bin or dat file is not displayed on lcd

**Comment by Cannonized** [comment]
All my .gcode files read 41 for size. Except offline_print.gcode

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 6, 2016 at 1:54 PM, clifford cannon<cliffordcannon101@yahoo.com> wrote:   None of the .guide files will print direct from the printer. It just shutters the print head and resets. Oh well at least printing with the computer attached and the file loaded on the SD card it works. 

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 6, 2016 at 1:45 PM, clifford cannon<cliffordcannon101@yahoo.com> wrote:   Oh maybe that's what I'm doing wrong is not saving.gcode. I didn't use USB core.cpp uploaded with arduino 1.6.5 r2, deleted the core call in one of the libraries. That's all in another thread though.

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 6, 2016 at 1:42 PM, Luc<notifications@github.com> wrote:   
Did you applied the usbcore.cpp from my github ? this prevent printer reset when usb connection is active and stopped not properly

does your file has an extension ? if no extension or extension is bin or dat file is not displayed on lcd

**Comment by luc-github** [comment]
how do you copy files to SDCard ? what FW version do you use ?

**Comment by Cannonized** [comment]
I'm using the latest one from your sync folder. Repetier host V1.6.0. Save file for SD printing from print preview section then upload from the SD card section. I'm going to buy the Toshiba air card that everyone recommends and give that a try eventually.

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 6, 2016 at 1:59 PM, Luc<notifications@github.com> wrote:   
how do you copy files to SDCard ? what FW version do you use ?

**Comment by Cannonized** [comment]
If all else fails I've found an arduino idea 1.5.8 beta that I might try and see if any of that makes it all work the way it's supposed to. Replace both the variant and usbcore files. Perhaps it's the workaround that I had to do with arduino 1.6.5r2 that's the problem.

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 6, 2016 at 2:05 PM, clifford cannon<cliffordcannon101@yahoo.com> wrote:   I'm using the latest one from your sync folder. Repetier host V1.6.0. Save file for SD printing from print preview section then upload from the SD card section. I'm going to buy the Toshiba air card that everyone recommends and give that a try eventually.

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 6, 2016 at 1:59 PM, Luc<notifications@github.com> wrote:   
how do you copy files to SDCard ? what FW version do you use ?

**Comment by luc-github** [comment]
if fix for due do not work - it is better to use master branch which is stable - sync branch is dev branch and not fully tested by me at least - for example I did not tested copy to SD functions

**Comment by luc-github** [comment]
About IDE : I use 1.6.5 with module for DUE 1.6.4 and do not have any compilation issue, no need to to workaround for path issue
So you may need to uninstall all and delete the arduino directory in Appdata to be sure your installation is clean
the arduino files are easy to be mess up with different version, if previous is not properly deleted before new version

**Comment by Cannonized** [comment]
OK I'll give the newest master a try. Again I had to do the work around not using the usbcore.cpp with arduino 1.6.5r2 that in itself could be the source of all my issues. Joys of modifications and hacking. Frustrating at times but oh so rewarding when it works right.

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 6, 2016 at 2:29 PM, Luc<notifications@github.com> wrote:   
if fix for due do not work - it is better to use master branch which is stable - sync branch is dev branch and not fully tested by me at least - for example I did not tested copy to SD functions

**Comment by luc-github** [comment]
I may have a solution - but cannot confirm - seems USB pins share a pin with filament sensor
now I isolated the pin properly - before was not 
here the change https://github.com/luc-github/Repetier-Firmware-0.92/commit/d5f899f687414b729a9c05332fbcff764f83c0f6
I only applied to 1.6.8 as it is the one i tested

**Comment by luc-github** [comment]
if no update/feedback I close issue

**Comment by luc-github** [comment]
I consider issue solved in 0.92.10

**Comment by bgauweiler** [comment]
I'm running into this issue with my freshly flashed Da Vinci 1.0A and Simplify3D if the print job takes more than 10 or 15 minutes to complete.  Printing pauses, after a few seconds, printing resumes.  I'm running the latest versions of your Repetier FW and S3D 3.1.0.

**Comment by luc-github** [comment]
Ho, thanks for sharing 

may I know your s3d settings for communication ?

**Comment by bgauweiler** [comment]
On September 20, 2016 at 7:39:46 PM, Luc (notifications@github.com) wrote:

Ho, thanks for sharing

may I know your s3d settings for communication ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/luc-github/Repetier-Firmware-0.92/issues/38#issuecomment-248477964>,
or mute the thread

**Comment by lonelymyp** [comment]
The same problem.

> SENT: G1 X65.168 Y110.690 E3.1003
READ: ok 0
SENT: G1 X63.032 Y80.002 F6000
SENT: G92 E0
READ: ok 0
READ: ok 0
SENT: G1 X102.024 Y118.995 E1.4577 F4800
READ: ok 0
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
READ: wait
WARNING: Firmware unresponsive. Attempting to force continue...
READ: ok 0
SENT: M105

> 

Save the G-code created from Simplify3D 3.1.0 to a file and ran this file for printing in repetier host.
file prints perfectly

**Comment by luc-github** [comment]
Thanks for sharing-
IMHO the main issue is that Davinci use Native Port and in someway windows drivers do not like it, linux is more `generic` for serial drivers.

May I know why you prefer to stream by serial instead of print from SD ? 

I did not know the issue with S3D and WiFi - good to know, thanks for the trick.
