### ISSUE TITLE
Heater/sensor fail even after load failsafe (master branch)

### ISSUE THREAD

**Issue by cpufreak** [luc-github/Repetier-Firmware-0.92#412]
I'm on a Da Vinci 1.0a model and just did the flash. I got to the part where it said to send the gcode M502 and M500. I opened up repetier, and it just threw "fatal: heater/sensor failure" and won't let me send the Gcode. I then also tried settings > Load fail-safe and selected "yes" to "store -> EEPROM" after where it confirms configuration stored. however even with restarts it's still showing heater/sensor fail. the printer worked just fine before the flash, what am I doing wrong??

**Comment by luc-github** [comment]
check the wires on your extruder it may be loose

**Comment by cpufreak** [comment]
I fixed it, it was user error. I accidentally set the 0 in the comment for MODEL to 1 instead of the value itself. thank you for the response though!

**Comment by luc-github** [comment]
no problem have a fun with your printer
