### ISSUE TITLE
Thermistor Wrong temperature reading

### ISSUE THREAD

**Issue by yoroboticscolombia** [luc-github/Repetier-Firmware-0.92#413]
Hi, I flashed the board of the davinci 1.0 with repetier, but the thermistor is reading 90C, I choosed the one from default that is option 5., Also changed other options but printer is halting due to wrong reading.

**Expected behavior**
Correct tempetature reading at ambient.

Compiled with Visual studio code.

**Printer
- Davinci 1.0 single extruder.

**Firmware Repetier.

**Comment by luc-github** [comment]
what is your printer 1.0 or 1.0A ? what did you change in your configuration file ?
You cannot change the thermistor tables they are defined according Model

**Comment by yoroboticscolombia** [comment]
Thanks, its 1.0A, the board is this one, 

![image](https://github.com/luc-github/Repetier-Firmware-4-Davinci/assets/62781222/1d85030c-e379-4f7c-9c52-fe5b7d9b6fde)

**Comment by luc-github** [comment]
any update ?
