### ISSUE TITLE
[Question]sam.h No such file or directory exist

### ISSUE THREAD

**Issue by ZADeveloperSmurf** [luc-github/Repetier-Firmware-0.92#414]
What is your question ?
I. have done exactly as your turotorial, and I keep on getting sam.h no such file or directory

I have used version 1.5.8, 1.6.5, 1.6.9, 1.8.9

Please help

**Comment by luc-github** [comment]
no idea what you are doing you do not describe anything
no diea what is your printer you do not explain anything
