### ISSUE TITLE
Davinci 1.0 Crashing / Resetting Mid Print

### ISSUE THREAD

**Issue by abwatson** [luc-github/Repetier-Firmware-0.92#50]
I have a Davinci 1.0 that worked 100% fine on Repetier .91. After upgrading to .92 I am having major issues with the printer crashing mid job. The LCD back light turns off then the printer immediately restarts and disconnects from my computer with no possibility of resuming. Does not happen after specific layers but after about 20 minutes to 45 minutes into the print. Cannot get a full successful print now. Ideas? 

Edit: Not a restart loop like others are stating happening every few seconds, but possibly a watchdog issue? I am unfamiliar with the function. Sorry if this is in fact a repeat issue.

**Comment by luc-github** [comment]
do you have more details ?
arduino version
variant.cpp version
host or sdcard printing
host version
if host any error in log monitor
when did you download the 0.92

it would help to understand where issue come from

**Comment by abwatson** [comment]
Yes, my apologies.

Arduino 1.6.0 with the latest variant.cpp posted in download for 1.6.0 (updated to .92 last Sunday 15th). I am host printing with Repetier 1.0.6.
No errors are present in log - Repetier sends coordinates, printer works for a strangely inconsistent amount of time and suddenly the printer restarts and says "printer ready" on LCD. 

10 minutes into a 2 hour print the printer restarts. I was able to resume with the unused gcode and start where i left off after heating back up the components. Roughly an hour later it happened again. Then about 30 minutes later, and then one final time before the print finished about 10 minutes later.
I re flashed 0.92 last night and was able to print a 30 minute, 33 layer print successfully. I am starting a larger print now, will know shortly if problem persists.

**Comment by luc-github** [comment]
Ok looks like USB connection issue
with 1.6.0 I did not add the usbcore.cpp, so if usb connection happen, printer freeze then watchdog restart it, usb connection issue come from cable or computer go to sleep or PC is too busy for a while an lock usb connection during a command.

If you did not change anything from cable / computer point of view, let check what can be done from FW point of view.
1 - stay with arduino 1.6.0 but replace the usbcore.cpp with the one in my github for the 1.5.8 they are identical between 1.6.0 and 1.5.8 so patch will work

if still have issue
2 - move back to arduino 1.5.8 and change variant.cpp/usbcore.cpp, Arduino 1.6.0 changed several things for serial/usb connection and it is pretty new - may be more changes are necessary but as I did not experienced any issue, I cannot guess if it is the root cause and where it come from....

if still have issue
3 - try SD Card printing 
this will allow to see if it is definitly USB issue or not

Until now I did several prints with 1.6.0 around 1h30min each and did not got any problem

**Comment by abwatson** [comment]
I have now changed the usbcore.cpp for the one in your github folder and re-flashed. I am now starting a new print, I'll reply when something (good or bad) happens. Thanks for your help so far.

**Comment by luc-github** [comment]
Ok let me know, I do not use USB connection since a while as no space in room close to printer, so I do not see all problems, thanks for your help

**Comment by abwatson** [comment]
No problem, I'm glad i can contribute to the community.
I am currently an hour and a half into a 10 hour print with no issues thus far after adding that usbcore.cpp file to arduiono. It's looking good so far, lets hope that's the fix for it. 
Will update again soon.

**Comment by abwatson** [comment]
Okay, **after reverting back to Arduino 1.5.8 and using both update files (variant.cpp/usbcore.cpp) I am no longer having USB or communication problems between printer and computer.** It seems to be functioning just as good as it was on .91 with the added bonuses of .92. 
Thank you very much for your help.
-Adam

**Comment by luc-github** [comment]
thanks for sharing, seems 1.6.0 is not fully compatible with the fw from usb point of view

**Comment by luc-github** [comment]
I have created an issue in the tracker to follow up
thanks

**Comment by abwatson** [comment]
Great, glad to be of assistance, should I reopen this issue? I assumed "close" meant me personally but did not think about the whole issue being not solved.

**Comment by luc-github** [comment]
no no it is correct, your issue it is solved in some way
I created issue https://github.com/luc-github/Repetier-Firmware-0.92/issues/51
for general following on this topic, and keep collecting information, I was just sharing I wanted to keep following issue
thanks for your concern

**Comment by abwatson** [comment]
Very well, Good luck in the future, and have a nice day.
-Adam

**Comment by jsnbrgg** [comment]
Hello..  I'm having the same issue with the printer restarting mid-print.  I'm running version 0.92 (downloaded again over the weekend to make sure I had the most recent version) and arduino 1.5.8.  I cannot print from USB at all, it restarts every couple minutes even when I'm not printing so long as I have the USB connected.  But when printing from the SD card it also reboots, it just waits much longer until it's in the middle of a 10 hour print.

Any suggestions would be appreciated?

**Comment by luc-github** [comment]
Looks like USB/Serial is blocked so this trigger the watchdog and reset printer

did you replaced the USBCore.cpp ?

**Comment by jsnbrgg** [comment]
Yes, I used the most recent version that you have in your download.  But it
even does this when no USB is connected and  it's printing from the SD card?

Thanks -J

**Comment by luc-github** [comment]
did you do any hardware modification ?
it was working before or never worked ?
You may try to disable watchdog to see what is wrong, to see if it is watchdog which reset or a short on some wires

**Comment by jsnbrgg** [comment]
I have an E3Dv6 hot end installed but it's always done this, even before
the hardware mod.  Short prints are OK usually but anything longer than 4
hours will randomly reset.  When it resets I can see the power cycling and
the printer comes back up.  I've checked and double checked all the wires
and can't find any sorts.

Last time I downloaded the firmware was Friday night.  Did you make any
updates since then?  Maybe I need to re-download again?

I turned off watchdog this morning and testing right now.

Thanks -J

**Comment by luc-github** [comment]
Yes just fixed an issue with G11.

Sorry you mentioned:
__it restarts every couple minutes even when I'm not printing so long as I have the USB connected.__
It start from power up or any action trigger this ?

**Comment by jsnbrgg** [comment]
The USB resetting doesn't start until I connect Repetier Host

**Comment by luc-github** [comment]
may  I know the settings you use in repetier host ?
what the log of repetier said ? any waiting command ?
So you never been able to use repetier host to print, it that correct ?
it is the same when you open a serial terminal in arduino IDE ?

**Comment by jsnbrgg** [comment]
Sure!  Give me a few minutes, I'm going to download the newest version of
firmware and load it.  Then I'll send some screen shots.

Thanks -J

**Comment by luc-github** [comment]
new fw need M502/M500 as it has new EEPROM positions

**Comment by luc-github** [comment]
ok nothing obvious, temperature of 250, looks high but not related to usb.
what about my others questions ?

**Comment by jsnbrgg** [comment]
I was last using the SD card, so I didn't have the host open.  I'll run it
this time and watch the log.

Correct, I've never been able to print reliably from the host.

I haven't tried it through the arduino IDE serial terminal.

Have the new firmware loaded on the printer now and I'm going to test it
out.  I will let you know what happens.

Thanks -J

**Comment by jsnbrgg** [comment]
Here are screen shots of the changes I made to the firmware configuration.h as I'm getting ready to load it now:

![image](https://cloud.githubusercontent.com/assets/11705977/6886352/53f23d8a-d608-11e4-9903-8fe9feaa5731.png)

![image](https://cloud.githubusercontent.com/assets/11705977/6886355/5f8c2b7e-d608-11e4-92fb-68dcbe0c704c.png)

![image](https://cloud.githubusercontent.com/assets/11705977/6886356/6e926c00-d608-11e4-8458-cbe2d12c28a5.png)

Thanks -J

**Comment by jsnbrgg** [comment]
The cheap filament I bought on eBay likes the temp at 250, lol

**Comment by luc-github** [comment]
to disable watchdog it is in variant cpp, uncomment disablewatch dog
to disable decouple test there is a flag in configuration.h , but decouple test do not reset printer just stop all

**Comment by jsnbrgg** [comment]
Ok.  I'm going to try it first with the newest firmware that I just
downloaded to see if that fixed my problem before I disable watch dog.

Thanks -J

**Comment by jsnbrgg** [comment]
Just started a print form the SD card.  I have the arduino serial running to see if I can catch the error if it fails.

Thanks -J

**Comment by jsnbrgg** [comment]
Well, it ran a couple hours and then restarted right in the middle of the print.  This was printing from a gcode file on the SD card, but this time I was monitoring the serial on the arduino.  I think it restarted on the TargetBed:100 line.  All the reset of the commands where just "wait".  Here's a screen shot:

![image](https://cloud.githubusercontent.com/assets/11705977/6887139/3de0dc4c-d624-11e4-8d0e-db5239117687.png)

Here is the latter part of the file:

![image](https://cloud.githubusercontent.com/assets/11705977/6887150/719e1112-d624-11e4-9471-9a58e74eb9e6.png)

So if I disable watchdog in the variant cpp file that wouldn't help right?  Since I'm not printing for the USB?  Or does it still look for that USB connection?

Thanks -J

**Comment by jsnbrgg** [comment]
The variant cpp file wasn't in the repetier sketch folder.  Should it have been?  I copied it over to that folder so it would open in the sketch tabs and I could get to it to edit it.

Thanks -J

**Comment by jsnbrgg** [comment]
I'm also going to give my bed a little more time for temp adjustments by changing this value; or at least I think that's what this does?

![image](https://cloud.githubusercontent.com/assets/11705977/6887263/f63b0882-d627-11e4-96c1-da3e2cc87261.png)

**Comment by jsnbrgg** [comment]
So, apparently I don't know how to disable watchdog because I'm getting all sorts of compile errors.  Can you please tell me the steps to disable it?

Thanks -J

**Comment by jsnbrgg** [comment]
Ok.. I have disabled Watchdog and now I'm starting the same print again except this time I'm running it from the host where I can watch the log.  It is a 5 hour print and the last four times I've tried it's reset about 2.5 to 3 hours into the print.  I've wasted a ton of filament on this, but I'm determined to figure out what the problem is before I start my 48 hour prints!

Thanks -J

**Comment by luc-github** [comment]
variant.cpp is in arduino directory in your system directory like usbcore.cpp they already exist, just replace the existing
to debug your issue it is better no to use filament - you will save time ( cleaning) and filament

**Comment by luc-github** [comment]
I see you are changing decoupled test values - why ? it is not related to watchdog , do you have decoupled error also ?

**Comment by jsnbrgg** [comment]
No, I was just grasping at straws.  Thought maybe the decoupling might be
causing the restarts until you mentioned earlier that the decoupling
doesn't do restarts.

It's been running for a while now from the host on USB with the watchdog
disabled.  Longer really than it's ever ran from USB since I changed the
firmware.  One thing that I'm noticing a lot is that it randomly stops like
it's buffering every few seconds, then continues.

Yes, if this print dies then I'm going to remove the filament until I get
the bugs worked out.

Thanks -J

**Comment by luc-github** [comment]
Strange - as others 1.0A seems not having this issue - are you using PC / linux / Mac ?

**Comment by jsnbrgg** [comment]
I'm using a Desktop PC with Windows 7 and I also tried my Microsoft Surface
Pro 3 with Windows 8 and had the same issues with both.

Thanks -J

**Comment by jsnbrgg** [comment]
Maybe I just got a lemon.  I've even been running it through my UPS to make
sure it's getting good clean power.

**Comment by luc-github** [comment]
well Davinci is very fragile, easy to get broken in a part when you fix another one, and easy to get fry

**Comment by jsnbrgg** [comment]
It's still running with no problems yet on USB with the watchdog turned
off.  So I'm wondering what are the hazards of leaving watchdog off to keep
my printer running?  Will the decouple still catch a problem while the
watchdog is off?

**Comment by luc-github** [comment]
yes decoupled test is working even watchdog is off that is why there a flag also for decoupled test to be disabled if needed

The watchdog is a protection for for out of control issue 
you may try to reenable watch dog but change the timer value to 16s
in HAL.H
// INTERVAL / (32Khz/128)  = seconds
#define WATCHDOG_INTERVAL       1024u  // 8sec  (~16 seconds max)

change to #define WATCHDOG_INTERVAL       2048u  // 16sec

to see if it help

**Comment by jsnbrgg** [comment]
Update:  It printed all night and completed the print from USB.  So my issue must be in the watchdog.  I'll try your watchdog settings later today and see how it goes.

Thanks! -J

**Comment by luc-github** [comment]
well if watchdog is triggered - it means there is a some problem - your board may have an issue so watchout

**Comment by jsnbrgg** [comment]
Thanks!  That is what I was thinking too.  I plan to only run it when I'm
home and can keep an eye on it while I have watchdog disabled.  Then later
I'll order an arduino and ramps to replace it, or maybe a factory Da Vinci
motherboard if I can find one.

-J

**Comment by jsnbrgg** [comment]
I've had a ton of problems with this thing.  If I lay a straight edge
across the bed, even the bed is slightly bowed so i always try to print in
the middle and the reason I changed the hotend was to try and solve the
issue with the random restarts.  But turns out I really like the E3D!  It's
less than six months old and had these problems straight out the box.
Didn't want to send it back though because I live in such a remote area
it's a major pain to ship something this large.  Plus I think I voided the
warrenty, lol

**Comment by jsnbrgg** [comment]
Just wanted to leave an update.  I've had the Watchdog disabled for about 16 days now and haven't had any more printer malfunctions.  I have not tried changing the Watchdog interval yet because it's been working so well.

Thanks

**Comment by luc-github** [comment]
good to read it is fine, happy printing :smile:

**Comment by jsnbrgg** [comment]
What did the update you made yesterday fix?  Was it related to this issue?

Thanks

**Comment by luc-github** [comment]
nope was a work around for people having issue with home sensor and that may make some shift during print - the issue is hardware but this can help to decrease the problem

**Comment by nobbynosecomb** [comment]
Hi I seem to be having a similar problem to jsnbrgg I just recently installed 0.92(about a week ago) and followed all the instruction changing the usb core file and variant ,all up loaded fine to my 1.0a I am using repetier host and slic3r all those settings seem right because what it does print looks great, my problem is the print will just stop randomly, show idle on the lcd and often say steppers disabled, the extruder and bed are still at full temp, sometimes I lose connection with the host as the bed is heating,  but regardless of when it happens there is absolutely no connection between the host and printer. I just tried to print a sample from the sd card option found in the printer lcd menu, it caused the printer to immediately try to start printing with a cold extruder and bed. Should I disable watchdog? im really not sure how to do that any help would much appreciated.

**Comment by luc-github** [comment]
you must not print sample file from XYZ using repetier it is not good as temperature are not in file that is why it start to print with cold extruder

if you loose connection when heating it means your repetier host settings are not corrects  (baud rate / ping pong...) or your usb cable/connector have issue.

you can disable watchdog but I think it won't help as watchdog reset the printer, and what you describe is not a reset of printer, but usb communication issue because if printer reset, temperatures will  be off.

As mentioned earlier in this  issue to disable watchdog you must edit the variant.cpp previously modified and   comment ```WDT_Disable(WDT);``` like this   ```//WDT_Disable(WDT);```

**Comment by nobbynosecomb** [comment]
Ok thank you for your quick reply I will double check those things and see how it goes ill leave watchdog alone

**Comment by nobbynosecomb** [comment]
ok I left my printer turned on and connected to the host with all manual commands working fine, and no printing activated.

 when I returned after 30 mins it had lost connection and I couldn't get it back untill i pulled the usb cable out ,and plugged it back in  I have the following settings cache 202 baud rate is 230400 on printer and in host ping pong is ticked

**Comment by luc-github** [comment]
what about others settings of repetier host ?

**Comment by nobbynosecomb** [comment]
![repetier connection](https://cloud.githubusercontent.com/assets/12810491/8206362/139b096a-153c-11e5-854d-6cde22d80325.png)

**Comment by nobbynosecomb** [comment]
let me know if you need any other settings I appreciate your help

**Comment by luc-github** [comment]
I see nothing wrong in setting so should be something else

is computer is going to standby ? this will shutdown connection and host do not like

**Comment by nobbynosecomb** [comment]
I installed repetier host and arduino on my laptop then copied all the same settings out of repetier and slicer,  and it printed with out any problems, maybe its a fluke, will try another print tomorrow,

 but if this continues to work from my laptop I guess there's a problem with my desktop considering there was little to no difference in the software and settings perhaps its a hardware or some windows settings on my desktop, any ideas?

**Comment by nobbynosecomb** [comment]
ill check the settings for standby also

**Comment by luc-github** [comment]
it is not in repetier settings as I can see -  so it is window settings (USB driver or power management) or hardware problem like a loose USB connector

**Comment by nobbynosecomb** [comment]
just a quick update im still trying to resolve this problem, this is what has happened recently, I started my comp and it crashed and blue screened, when I restarted it it did a restore after which everything was working fine, and I was able to do 3 prints all around 2 hours each, on the 4th print it lost connection again at around layer 50/103.

 Today I have disabled usb in power management which didnot help I have reloaded usb drivers and changed usb sockets about 4 times now, one thing I have noticed is when it loses connection and I try to reconnect using the host it says that the port no longer exists, and when I unplug/plug the usb back into the same port, it assigns a different number to the port I am now up to com 12 is that normal?

 I have never had any issues with this comp in the past while running my printer,
 is it likely to be a  motherboard issue or maybe I need to reinstall  windows any ideas would be appreciated.

**Comment by luc-github** [comment]
Well can be drivers problem, can be usb chip issue - may be BIOS setting /issue
many possibility actually

It is windows which assign the port name - you may try to update arduino drivers using latest IDE (no need to flash with it, just let arduino drivers to be updated,  and DO NOT FLASH using any 1.6.x ide)

**Comment by nobbynosecomb** [comment]
Quick update the problem is now resolved,I believe the installation of the latest Arduino drivers or a disc repair of that comp did the trick, it is now printing amazingly.

 On another point does a high end graphics card have any bearing on printer quality or function ?
thanks for all your help and support Luc.

**Comment by luc-github** [comment]
no - graphical card may have impact on rendering only not on printing /slicing

**Comment by 3DPrintedPug** [comment]
Hi My printer has been having issues with the heater decoupling and I was wondering how I could fix it.

**Comment by luc-github** [comment]
please open new issue as this is not related to watchdog neither printer resetting and right now there are too many unrelated issues in thread  
Check your sensor connectors it is likely a connection issue / you can also  disable decouple test in configure.h

**Comment by Dennis38** [comment]
I am having the same issue Da vinci 1.0A running repetier .92 the printer was working no problem's then all of a sudden it started stopping randomly during a print i have gone back over everything i have read here short of reflashing the eeprom and it still dose the same thing i have changed cable looked at windows setting's ETC when the printer dose this the log file shows the last Gcode and then it looks like it jumps back and says Wait,Wait and this gose on unitl i shut it down I can't close the connection to the printer from the host i am running a pc windows XP baude rate is 230400 i have tried speeding up the printer slowing it down nothing seams to work any help is greatly apprecaited Thanks

**Comment by luc-github** [comment]
Looks USB communication issue -  flashing FW / EEPROM won't change/solve anything

check your printer environement, if electrical / network cable are close to printer it may disturb signal
check your connector on printer/PC to ensure it is not loose
check your settings your host is using also you do not mention what host you are  using

**Comment by Dennis38** [comment]
Hello Luc 
Thank you for your response I am using repetier host V 106 i tried another cable same thing happened the printer cable maybe near the power cable for the computer i will move it should i put some shielding over it ? i am using slic3r that is with the repetier host program the printer runs fine just stops in the middle of the print at random points.

Thanks Dennis

**Comment by luc-github** [comment]
it may not be the cable it self, it can also be the connectors on PC or Printer

did you tried forcing using repetier protocole instead of autodetect?, it has better error check

also decrease baud rate must be done on host and printer and must  match, is what you did ?

**Comment by Dennis38** [comment]
Luc thanks you for your response. 
I put the cable in another usb port same problem, yes i changed the baude rate in the host and the printer to match, question could it be the stl file it self i run any downloaded files through netfab and Rhino to check them so i wouold not think it to be the files themselves ?

**Comment by luc-github** [comment]
could be several root cause - yes you can try netfab to check the stl
you can also try to print from SDCard
you can also use latest repetier host 1.5.2 as 1.0.6 does not support repetier protocol V3 but only V2

**Comment by Dennis38** [comment]
host 1.5.2 is this the one with filament retract if so i tried it and did not like the print it came out with high bumps on the top of the part

**Comment by luc-github** [comment]
"host 1.5.2 is this the one with filament retract " not sure what do you mean or what is the issue
As I print from SDCard using S3D as slicer, I am not familiar with Repetier host issue

**Comment by Dennis38** [comment]
Luc 
In the 1.5.2 version it included a feature that is supposed to releave pressure in the extruder i think this is supposed to help stop material from coming out of the nozzle what i found is that everytime the software performs this feature it causes the filament to push out leaving a bump of plastic as the machine goses through the print it get's higher and higher and soon the extruder start's hitting it causing a shutter, so i went back to the previous version of sli3r.
  Something new i did a design in Rhino 3d saved it as a STL file and did a dry run on the printer it ran for 1 hour 43 minutes and completed the gcode with out a problem so now i don't know where i am with this problem if i download a file from say thigiverse to print could it be the file i would think that if the file were the problem it would show up in netfab or slic3r .

**Comment by luc-github** [comment]
I think retractation issue you are facing is a setting set with wrong value not new feature.
retractation for davinci should be around 2mm but   default slicer is 4mm usually

**Comment by luc-github** [comment]
in addition you should be aware that a lot of thingiverse items are actually no printable as it is because not manifold and need to be fixed 
and even fixed they can failed for construction issue not compatible with 3d printing

**Comment by Dennis38** [comment]
Luc 
OK i will get the version 1.5.2 and make the retraction adjustment as you noted, but when slic3r says it's a manifold i would think the file is printable i will look into this futher i can't thank you enough for your help, support and great work on this firmware i will let you know how thing's go from here.

**Comment by luc-github** [comment]
please have a look here - there are some explaination and some website to check stl

https://3dfizzr.wordpress.com/2013/08/05/how-to-check-you-stl-files-before-3d-printing-them/

**Comment by Dennis38** [comment]
Luc
Thank you and will have a look at that.

**Comment by Dennis38** [comment]
Luc 
Recently tried printing a part i designed in rhino made it in 2 parts first part printed no problem printer ran for over 2 hr's next day tried to print the second part and the printer stoped after 20 minutes so it's not the file any news on a fix for this problem.

Dennis

**Comment by Dennis38** [comment]
Today working on the printer crashing i increased the size of the buffer to 250 and checked the ping pong box and then tried printing the same file the printer crashed on, i did a dry run the printer ran the entire print i have all the dialog items turned to monitor any problems is this to much for the software to keep up with should i turn it all off.
What is the buffer size that i should be running with repetier .92 and the da vinci 1.0a

**Comment by luc-github** [comment]
You can try the settings provided here:
https://github.com/luc-github/Repetier-Firmware-0.92/issues/38 to see if improve 

you also can try the patch here (1 line to change in hal.cpp): 
https://github.com/repetier/Repetier-Firmware/pull/425#issuecomment-139915216
but seems not fully solving the issue.

In all cases this FW issue - I follow repetier issue to apply any patch when confirmed working as repetier is working on it.

**Comment by luc-github** [comment]
You can try the settings provided here:
https://github.com/luc-github/Repetier-Firmware-0.92/issues/38 to see if improve 

you also can try the patch here (1 line to change in hal.cpp): 
github.com/repetier/Repetier-Firmware/pull/425#issuecomment-139915216
but seems not fully solving the issue.

In all cases this FW issue - I follow repetier issue to apply any patch when confirmed working as repetier is working on it.

I never had this issue with repetier - only with s3d so these are may be 2 issues together not only one

**Comment by Dennis38** [comment]
OK i will make the changes, but what i find is the buffer is empty and it never retries to resend the data so maybe the cache increase will help or be the answer to the problem with small parts the printer seams to work fine but in larger and longer run time this is when it quits i have run the printer on windows 7 and xp no difference.

Dennis

**Comment by Dennis38** [comment]
OK So i changed the buffer size and added ping pong to the printer and ran the file the printer crashed on it ran all the way through the g-code without crashing length of run time 2hrs 30 minutes so i guess i am on the right road luc i could not find the file you mentioned above but my thanks for your help.

Dennis

**Comment by luc-github** [comment]
Well ping pong is a control to ensure communication is Ok - for me it is mandatory to set it to get good communication between host and printer.

**Comment by Dennis38** [comment]
Luc 
OK then i did the right thing there what about the cache size is there a limit for this.

Dennis

**Comment by luc-github** [comment]
For the cache I do not have special recommendation as I always used default values but seems increasing cache solve some issue with S3D so it could be same with repetier:
https://github.com/luc-github/Repetier-Firmware-0.92/issues/38#issuecomment-115025217
he used 2024 - you can give a try.
I do not use usb at all sorry

**Comment by Dennis38** [comment]
Luc 
After the changes increasing the cache size and pingpong i have done several prints and the machines runs great no crashes at this time.

Dennis

**Comment by luc-github** [comment]
Good, so solution for S3D is also valid for repetier
Thank you for your feedback

**Comment by Dennis38** [comment]
Luc 
Your welcome and thank you for your time and work
