### ISSUE TITLE
2/26 Dav1.0 power cycles every 18-19 seconds (edit:user error).

### ISSUE THREAD

**Issue by Nepenthy** [luc-github/Repetier-Firmware-0.92#54]
Sorry I cant be more specific. I was @ 2/20 and today went to 2/26 on a Dav1.0. After successful flash machine power cycles every 18-19 seconds. Please let me know if theres anything I can do to help narrow something down.

**Comment by luc-github** [comment]
no idea what is wrong as am doing a test print right now and already printing  4 hour
be sure no file is corrupted and reflash
if still issue go back to previous commit download the corresponding set and flash it , and do it until no more issue, normally the previous one you used
another test is to disable watchdog in variant.cpp and configuration.h to avoid restart and see what is wrong

**Comment by luc-github** [comment]
just checked last commit was to fix an issue for 1.0 and was validated on 1.0 so should be ok, unless you do some change in configuration.h that I am not aware

**Comment by luc-github** [comment]
not sure you know how to select a commit , here the way
to go to previous commit on github.com
click latest commit
![image](https://cloud.githubusercontent.com/assets/8822552/6426513/ec9cd214-bf99-11e4-94e0-194789cc0ef5.png)
then click on parent id
![image](https://cloud.githubusercontent.com/assets/8822552/6426522/84c58f9a-bf9a-11e4-98f4-b749f0cef5a6.png)

then browse files
![image](https://cloud.githubusercontent.com/assets/8822552/6426528/b1d7f838-bf9a-11e4-876b-dccdc765f23e.png)

then you can see the commit id and can download the corresponding sources by clicking on download zip

![image](https://cloud.githubusercontent.com/assets/8822552/6426539/31aebfe2-bf9b-11e4-994e-569609ae05c0.png)


you can navigate from commit to commit like this

**Comment by luc-github** [comment]
sorry it is almost 11pm here now so will check your feedback tomorrow

**Comment by Nepenthy** [comment]
This was my stupid mistake so im going to remove it. I had noticed that I still saw the heatbed init in the config, after reading it was removed, but didnt pay much attention. Going back I see I had edited and flashed the wrong version:
#define VERSION_MINOR_YEAR "14"
#define VERSION_MINOR_MONTH "12"
#define VERSION_MINOR_DAY "12"
#define VERSION_BUILD "1"

#define WARMUP_BED_ON_INIT 0 

My apologies for false alarm.

**Comment by luc-github** [comment]
ok good news so, it is scary issue
