### ISSUE TITLE
Changing the thermistor for a standard 100k

### ISSUE THREAD

**Issue by laptopdude90** [luc-github/Repetier-Firmware-0.92#72]
So, my bed broke and I'm replacing it with a reprap heated bed. Can I use a 100k thermistor to replace the current one?

**Comment by luc-github** [comment]
Yes you can use it, but you may need a custom table as sensor tables are usually made to be used with Ramps not DaVinci Board- this is same for extruder.

**Comment by luc-github** [comment]
you can refer to what we did for current bed : measurement are not easy to be accurate and reproductible
https://github.com/luc-github/Repetier-Firmware/issues/83

**Comment by luc-github** [comment]
If nothing more on this - I close issue

**Comment by luc-github** [comment]
adding link to explaination for referencehttp://voltivo.com/forum/davinci-firmware/438-repetier-91-e3d-v6-extruder#3631
