### ISSUE TITLE
Printer reboot during printing

### ISSUE THREAD

**Issue by Doudou14** [luc-github/Repetier-Firmware-0.92#73]
hi !

By printing a piece of 6H, the printer is stopped and reboot after 1:30 hour. On the log repetier I type commands from the layer 31: Unknown command: Nxxxxx M106
The printer reboot on the layer 43.

Is it due to the watchdog, the power from the printer or other?

Thanks !

**Comment by luc-github** [comment]
M106 is fan command that is not implemented unless repurpose fan define is set, it does not generate a reboot
reboot is may done by watchdog but the root cause can be several possibilities

I already printed several times more than 8h without issue

**Comment by Doudou14** [comment]
How do I know if this is the watchdog that caused to reboot?

**Comment by luc-github** [comment]
you can disable it, uncomment disablewd in variant.cpp

**Comment by Doudou14** [comment]
I will try, thank you

**Comment by luc-github** [comment]
If nothing more on it I close it
