### ISSUE TITLE
Z Offset doesn't apply when calibrating

### ISSUE THREAD

**Issue by laptopdude90** [luc-github/Repetier-Firmware-0.92#79]
I'm trying to use a standard Repetier heatbed and glass with my Davinci 1.0a. It's about 5mm thick, so I'm using an offset of 5mm. However, when I calibrate, the hotend runs into the bed. Any way to fix?

**Comment by luc-github** [comment]
you need to do a proper bed leveling at Zoffset=0 using the screws 
Unlike stock fw, repetier fw allows you to do anything if you have 5mm offset instead of bed leveling properly and you do a Z homing alone with the noozle on middle of the bed you will break your glass.

Z offset is for small adjustment, fine tuning, not such big gap, for big gaps you need to use the screws under the bed and  do a proper bed leveling

**Comment by laptopdude90** [comment]
The screws don't go far enough, unfortunately.

Can I somehow level it with gcode?

**Comment by luc-github** [comment]
well there is a way but it won't prevent any accident if you do Z homing alone and I do not know if it is reliable :
in configuration.h line 844 ```#define ENDSTOP_Z_BACK_ON_HOME 0```
try ```#define ENDSTOP_Z_BACK_ON_HOME 5``` or what ever the value you need it should drop bed to 5mm after homing and set this new position to Z = 0

Another solution, hardware this time, print a longer flag (+5mm or what ever you need) for the Z end stop, people who mod their DAVINCI with EDV6 extruder without changing carriage use this mod as  
extruder nozzle is longer than stock one so they are in same situation as you.

**Comment by luc-github** [comment]
here the flag : http://www.thingiverse.com/thing:621440

**Comment by laptopdude90** [comment]
Oh, I like the hardware solution. Going to have to try that out.

**Comment by luc-github** [comment]
IMHO this is the safer one

**Comment by laptopdude90** [comment]
Any idea on a temporary one I can use? Obviously, I can't print one off.

**Comment by luc-github** [comment]
I suggest you to test the software solution it should allow you to print the flag - just do not use Z home alone but Home all

**Comment by laptopdude90** [comment]
Hmm, I'll try that, but first I'm going to try a DIY hardware thingy, like maybe a piece of wood, or some rigid stick notes.

**Comment by luc-github** [comment]
flag need to be black -  I cannot recommand anything as I do not know what 1.0A end stop looks like, XYZ change their hardware and have at least 2 kinds

**Comment by laptopdude90** [comment]
Confirmed working, stuck a sticky note on the metal bit.

**Comment by luc-github** [comment]
good - if you do a new flag design please share it - would be helpful

**Comment by laptopdude90** [comment]
I plan on designing one eventually.

**Comment by luc-github** [comment]
Ok Happy printing :smile:

**Comment by luc-github** [comment]
I close issue then
