### ISSUE TITLE
gcode to turn Lights on

### ISSUE THREAD

**Issue by celevra** [luc-github/Repetier-Firmware-0.92#97]
Hi,

is there a special code i can send to turn the lights an?
With the regular switch in repetier-host nothing happens, if i go thrugh settings directly on the printer i can turn the lights on an off.

regards

Philipp

**Comment by luc-github** [comment]
all codes are here : https://github.com/luc-github/Repetier-Firmware-0.92/blob/master/src/ArduinoDUE/Repetier/Repetier.ino

M355 S<0/1> - Turn case light on/off, no S = report status, (no eeprom saving) and reset autoturn off time if activated

**Comment by luc-github** [comment]
"With the regular switch in repetier-host nothing happens," there is a switch for light in repetier host ?

**Comment by celevra** [comment]
![bildschirmfoto 2015-07-22 um 15 19 01](https://cloud.githubusercontent.com/assets/232437/8826295/b845bf1e-3085-11e5-9f10-0d2d5956476b.png)

repetier-server i'm sorry, for repetier-host i've written a simple script with the right gcode in it.

like magic it started working from repetier server after doing it manualy through the gcode...

thanks again for your help!

**Comment by luc-github** [comment]
good to know - I do not use repetier server - I should give a try
